### ISSUE TITLE
Bookmarks are displayed twice after installing a new module

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1851] opened 2021-10-14 00:36 UTC
I don't think there should be a double speak bookmark created.
I believe when I installed a czech module and tried to speck it with an English synthesizer it displayed a msg box saying no language available. But it cause a bookmark to be added to the verse each time.
![Screenshot_20211013-172946_Bible Study](https://user-images.githubusercontent.com/46405809/137231181-439d3546-7beb-4773-99a5-9b180675de3c.jpg)

**Comment by tuomas2** [comment] 2023-01-07 08:47
I noticed this happening for normal bookmarks here:

https://support.andbible.org/scp/tickets.php?id=1745

**Comment by tuomas2** [comment] 2023-01-07 09:59
Probably reproducible after installing (or uninstalling) a module.

**Comment by tuomas2** [comment] 2023-01-07 09:59
I think I remember some (similar?) bug reported by @mattschlosser in the past... was it duplicate of this?

**Comment by timbze** [comment] 2023-01-07 15:30
I think #1965 and #1623 are the same issue

**Closed as completed by timbze** 2023-01-07 15:30 UTC
Labels: Type: Bug

**Comment by timbze** [comment] 2023-01-07 15:33
#2203 tracks multiple issues that are similar with possibly same root cause.
