### ISSUE TITLE
AndBible jumps to the beginning of chapter when two windows are open... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#381] opened 2019-05-31 00:37 UTC
1) Open two Bible windows of different translation.
2) minimize second window.
3) go to Daniel chapter 2, and page up to verse 19.
4) tap on second window to split the view.
5) on the second window go up one verse.
6) tap and hold on the win. menu of the second window to minimize it.

The first window jumps to the beginning of the chapter. It should stay on verse 20

This is happening in build 310.

**Comment by tuomas2** [comment] 2019-05-31 12:09
Reproduced with build 310

**Comment by tuomas2** [comment] 2019-05-31 13:30
Actually I'm reproducing similar problem #382.

I was able to reproduce this too once, but  not any more. Probably there's some missing step in bug report. Though this is so similar as #382 that I believe this will be fixed when #382 is fixed.

**Comment by tuomas2** [comment] 2019-06-01 14:38
Possible fix: 97fc1d37c30a6a1195158afd953d8a515387cef9

**Comment by tuomas2** [comment] 2019-06-01 20:31
Could you @bvahedy check if this reproduces still in build 311 (just released)?

**Comment by bvahedy** [comment] 2019-06-02 04:31
So far seems to be working, I'll close this ticket.

**Comment by tuomas2** [comment] 2019-06-02 15:57
Got this again today :-( So this bug is still there, but hiding most of the time.

**Comment by tuomas2** [comment] 2019-06-07 07:25
I got following log from this (or similar) problem. I was in maximized mode. In ESV Study bible I had position Rev.14.14, but when I moved to synchronized ESV window, it jumped to Rev:14:19. 

```
2019-06-07 10:17:29.933 24582-24582/? D/BibleView: Detached from window
2019-06-07 10:17:29.933 24582-24582/? D/BibleView: Pausing tilt to scroll Window [screenNo=15]
2019-06-07 10:17:29.955 24582-24582/? D/BibleView: Attached to window
2019-06-07 10:17:29.958 24582-24582/? I/chatty: uid=10310(net.bible.android.activity) identical 2 lines
2019-06-07 10:17:29.962 24582-24582/? D/BibleView: Executing JS:setToolbarOffset(80.0);
2019-06-07 10:17:29.962 24582-24582/? I/chatty: uid=10310(net.bible.android.activity) identical 1 line
2019-06-07 10:17:29.962 24582-24582/? D/BibleView: Executing JS:setToolbarOffset(80.0);
2019-06-07 10:17:29.962 24582-24582/? D/BibleView: Executing JS:setToolbarOffset(0.0);
2019-06-07 10:17:29.963 24582-24582/? D/BibleView: Pausing tilt to scroll Window [screenNo=16]
2019-06-07 10:17:29.963 24582-28096/? D/net.bible.service.sword.SwordContentFacade: Using fast method to fetch document data
2019-06-07 10:17:29.963 24582-24582/? D/net.bible.service.sword.SwordDocumentFacade: Getting bibles
2019-06-07 10:17:29.963 24582-24582/? D/net.bible.service.sword.SwordDocumentFacade: Got bibles, Num=19
2019-06-07 10:17:29.965 24582-24582/? D/net.bible.service.sword.SwordDocumentFacade: Getting books of type Commentaries
2019-06-07 10:17:29.965 24582-24582/? D/net.bible.service.sword.SwordDocumentFacade: Got books, Num=5
2019-06-07 10:17:29.965 24582-24582/? D/net.bible.service.sword.SwordDocumentFacade: Getting books of type Lexicons / Dictionaries
2019-06-07 10:17:29.965 24582-28096/? D/net.bible.service.font.FontControl: Book:ESV2011 Language code:en Font:null
2019-06-07 10:17:29.965 24582-24582/? D/net.bible.service.sword.SwordDocumentFacade: Got books, Num=5
2019-06-07 10:17:29.966 24582-24582/? D/BibleView: Resuming tilt to scroll Window [screenNo=13]
2019-06-07 10:17:29.966 24582-24582/? D/BibleView: Pausing tilt to scroll Window [screenNo=15]
2019-06-07 10:17:29.966 24582-24582/? D/BibleView: Pausing tilt to scroll Window [screenNo=-999]
2019-06-07 10:17:29.979 24582-28096/? D/net.bible.service.sword.SwordContentFacade: Using fast method to fetch document data
2019-06-07 10:17:29.982 24582-28096/? D/net.bible.service.font.FontControl: Book:FinSTLK2017 Language code:fi Font:null
2019-06-07 10:17:29.989 24582-28096/? D/UpdateTextTask: Loading document:ESV MacArthur Study Bible Commentary key:Revelation of John 14:12
2019-06-07 10:17:29.989 24582-28096/? D/net.bible.service.sword.SwordContentFacade: Using standard JSword to fetch document data
2019-06-07 10:17:29.990 24582-24582/? D/BibleView: Show(html,ChapterVerse(chapter=14, verse=12),-1.0) Window:Window [screenNo=13]
2019-06-07 10:17:29.990 24582-24582/? D/net.bible.service.font.FontControl: Book:ESV2011 Language code:en Font:null
2019-06-07 10:17:29.991 24582-28096/? D/net.bible.service.font.FontControl: Book:ESV MacArthur Study Bible Commentary Language code:en Font:null
2019-06-07 10:17:29.992 24582-28096/? D/ReferenceHandler: Ref:ESV MacArthur Study Bible Commentary:Rom.8.31-Rom.8.39 Content:Rom. 8:31–39
2019-06-07 10:17:29.994 24582-24582/? D/BibleView: Executing JS:registerVersePositions()
2019-06-07 10:17:29.994 24582-24582/? D/BibleView: Scroll or jump to:ChapterVerse(chapter=14, verse=9)
2019-06-07 10:17:29.994 24582-24582/? D/BibleView: Executing JS:scrollToVerse('14.9', true, 80.0)
2019-06-07 10:17:29.994 24582-24582/? D/BibleView: Scroll or jump to:ChapterVerse(chapter=14, verse=12)
2019-06-07 10:17:29.994 24582-24582/? D/BibleView: Executing JS:scrollToVerse('14.12', false, 80.0)
2019-06-07 10:17:29.994 24582-24582/? D/BibleView: Show(html,ChapterVerse(chapter=14, verse=6),-1.0) Window:Window [screenNo=16]
2019-06-07 10:17:29.995 24582-24582/? D/net.bible.service.font.FontControl: Book:FinSTLK2017 Language code:fi Font:null
2019-06-07 10:17:29.995 24582-28096/? D/ReferenceHandler: Ref:ESV MacArthur Study Bible Commentary:Rev.6.1 Content: 6:1–19:21 This lengthy section...
2019-06-07 10:17:29.996 24582-24582/? D/BibleView: Scroll or jump to:ChapterVerse(chapter=14, verse=9)
2019-06-07 10:17:29.997 24582-24582/? D/BibleView: Executing JS:scrollToVerse('14.9', false, 80.0)
2019-06-07 10:17:29.997 24582-24686/? D/BibleJavascriptIntrfc: clear verse positions
2019-06-07 10:17:29.999 24582-24686/? D/BibleJavascriptIntrfc: Num spans found:80
2019-06-07 10:17:30.000 24582-24582/? D/BibleView: onLoadResource:data:text/html;charset=utf-8;base64,
2019-06-07 10:17:30.002 24582-24686/? D/BibleJavascriptIntrfc: Num verses found:20
2019-06-07 10:17:30.021 24582-24582/? D/BibleView: onLoadResource:data:text/html;charset=utf-8;base64,
2019-06-07 10:17:30.075 24582-24686/? D/BibleJavascriptIntrfc: Enabling verse long touch selection mode
2019-06-07 10:17:30.082 24582-24686/? D/BibleJavascriptIntrfc: JS onload
2019-06-07 10:17:30.083 24582-24686/? D/BibleJavascriptIntrfc: onLoad from js
2019-06-07 10:17:30.084 24582-24686/? D/BibleJavascriptIntrfc: clear verse positions
2019-06-07 10:17:30.084 24582-24686/? D/BibleJavascriptIntrfc: Num spans found:80
2019-06-07 10:17:30.084 24582-24686/? D/BibleJavascriptIntrfc: Num verses found:20
2019-06-07 10:17:30.092 24582-24686/? D/BibleJavascriptIntrfc: Enabling verse long touch selection mode
2019-06-07 10:17:30.099 24582-24686/? D/BibleJavascriptIntrfc: JS onload
2019-06-07 10:17:30.100 24582-24686/? D/BibleJavascriptIntrfc: onLoad from js
2019-06-07 10:17:30.100 24582-24686/? D/BibleJavascriptIntrfc: clear verse positions
2019-06-07 10:17:30.101 24582-24686/? D/BibleJavascriptIntrfc: Num spans found:84
2019-06-07 10:17:30.101 24582-24686/? D/BibleJavascriptIntrfc: Num verses found:21
2019-06-07 10:17:30.346 24582-24582/? D/BibleView: Scroll or jump to:ChapterVerse(chapter=14, verse=9)
2019-06-07 10:17:30.347 24582-24582/? D/BibleView: Executing JS:scrollToVerse('14.9', false, 80.0)

```

**Comment by tuomas2** [comment] 2019-10-17 12:36
Should be fixed as well in build 315. Please check properly however. I made fixes to js interface and can't reproduce this any more.

**Closed by tuomas2** 2019-10-17 12:36 UTC
Labels: Affects: Beta, Type: Bug

**Comment by bvahedy** [comment] 2019-10-18 03:18
This is now fixed in build 315.
