### ISSUE TITLE
Dictionary slower than Bible

### ISSUE THREAD

**Issue by oxr463** [AndBible/and-bible#563] opened 2020-03-01 19:25 UTC
**Describe the bug**

Looking up a word in the dictionary is much slower than looking up a verse in the Bible.

**Bug was found on And Bible version**
Version: 3.2.333

**To Reproduce**
1. Go to Main Menu
2. Click on Choose Document
3. Click on Webster1913
4. Attempt to search for a word

**Expected behavior**
Dictionary should allow quick lookup for words.

**Screenshots**
![Screenshot_20200301-142232](https://user-images.githubusercontent.com/43783393/75632254-40626b00-5bc8-11ea-8493-120af90337ed.png)

**Smartphone (please complete the following information):**
 - Device: Vivo One Plus 2019
 - OS: Android
 - Version: 8.1.0

**Additional context**
Searching in the Bible itself is much quicker.

**Comment by bvahedy** [comment] 2020-03-01 23:02
Running 3.2.340, on initial load there is a 3 sec. pause but after that all word look ups are fast.

**Comment by oxr463** [comment] 2020-03-02 00:07
How are you profiling it?

**Comment by bvahedy** [comment] 2020-03-02 01:12
What do you mean by "profiling it"?

**Comment by oxr463** [comment] 2020-03-02 01:51
How did you arrive at 3 seconds? Are you using a Java profiler, or did you just count it out while waiting?

**Comment by bvahedy** [comment] 2020-03-02 02:00
Just count it out while waiting, but that only happens on initial load not for every word search.

**Comment by oxr463** [comment] 2020-03-02 02:07
How can we fix it?

**Comment by bvahedy** [comment] 2020-03-02 04:42
I have a feeling it's loading or building a quick search index initially but that's a question for Tuomas. It would have to be prioritized and looked at by him.

**Comment by tuomas2** [comment] 2020-05-09 12:14
@oxr463 I just tried this with the latest build (367) and did not notice too much of a lag. I have changed the loading code after you have tried it. Can you try again and let me know if the problem still persist?

First time it takes maybe second or two (wall time, did not block the UI) but second and following new lookups were quick.

**Comment by tuomas2** [comment] 2020-05-09 12:15
Please re-open if the issue is still there. Closing for now.

**Closed by tuomas2** 2020-05-09 12:15 UTC
Labels: Prio: Major, Type: Bug

**Comment by oxr463** [comment] 2020-05-09 12:43
> @oxr463 I just tried this with the latest build (367) and did not notice too much of a lag. I have changed the loading code after you have tried it. Can you try again and let me know if the problem still persist?
> 
> First time it takes maybe second or two (wall time, did not block the UI) but second and following new lookups were quick.

Where can I get this?

**Comment by tuomas2** [comment] 2020-05-09 14:30
Beta releases are on beta channel of Google Play as well as here: https://drive.google.com/drive/folders/1LpUarFDZG8niDVC7JJufs0odV33s1z8D

**Comment by Noitarud** [comment] 2025-02-10 05:57
this annoys me too (5.0.735 with tablet on low battery, it is 11s) and I think there is a simple solution - activate the search field **before** doing the "3 sec" process, this will cause the keyboard to appear and the user can begin to input the query. The app will be hanging and not display characters until it resumes drawing.
