### ISSUE TITLE
Search across multiple translations

### ISSUE THREAD

**Issue by alan2675** [AndBible/and-bible#2556] opened 2023-04-01 13:01 UTC
Provide a way to search for words or phrases when you aren't sure which translation they are in.
(Just use the installed translations for which an index already exists.  Or provide a list of indexed translations with check boxes to select the ones to be searched)
Iterate across the selected indexed translations performing the search as usual.
In the result, show the translation (bible name) along with the verse for each instance that was found.

Example:  search Matthew for "hallowed".  It should return Mat 6:9 in KJV and NASB but not WEB and NET.

**Comment by timbze** [comment] 2023-04-16 10:49
Closing as duplicate of #2455

**Closed as completed by timbze** 2023-04-16 10:49 UTC
Labels: Type: Feature
