### ISSUE TITLE
Calculator app after update doesn't open after first entry of the code...

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#2687] opened 2023-07-24 02:04 UTC
Affects latest beta 706 build: 

After installing the update to the calculator app, the code to enter  Andbible does not open the app.  Initially I thought I had entered the wrong code.  But this happened with the last couple of beta builds. So I made sure the code was correct on first try. 
Once the app opens, all Subsequent entries work on first try.

**Comment by tuomas2** [comment] 2023-07-27 06:04
How do you start the app? I tried with 710 build and it works perfectly with first try when I start app from app launcher icon.

**Comment by bvahedy** [comment] 2023-07-27 15:28
I'm on 707 build and it still happens. I open the app by taping on the app icon from the home screen. 
 I will try 710 build and will let you know if it's still happening.

**Comment by bvahedy** [comment] 2023-07-27 15:44
I tried 713 beta build, and it's still happening.

**Comment by tuomas2** [comment] 2023-07-29 08:55
Okay got it reproduced now on my mobile phone.

**Comment by bvahedy** [comment] 2023-07-29 17:59
Thank you, I though I was going insane. You start doubting yourself did I hit the equal button properly? Hopefully it's an easy fix, though nowadays nothing comes easy.

**Comment by tuomas2** [comment] 2023-08-01 17:24
Not fixed yet but noting here that it is caused by recent night mode fix.

**Comment by bvahedy** [comment] 2023-08-01 20:09
Ok thx.

**Comment by tuomas2** [comment] 2023-08-26 09:09
should be fixed now

**Closed as completed by tuomas2** 2023-08-26 09:09 UTC
Labels: Type: Bug, Affects: Beta
