### ISSUE TITLE
Can't download or build greek index

### ISSUE THREAD

**Issue by kentprimrose** [AndBible/and-bible#103] opened 2017-11-29 12:43 UTC
Downloading or building an index fails - initial search after download or build gives "Invalid search query", and searching again results in an "upside down android symbol", and searching again after restarting requires download or build of the index again.

Steps to produce:
1. Install MorphGNT bible and StrongsRealGreek dictionary.
2. Navigate to John 1 in MorphGNT with Morphological codes displayed.
3. Tap 0746 beside the second word (arche).
4. Tap "Find all occurrences" in the "Real Greek" window.
5. You are asked to "DOWNLOAD" or "CREATE" an index. Do either.
6. After downloading (or creating) you get a dialog "Invalid search query"
7. Click OK
8. You return to the "arche" window for "Real Greek".
9. Click "Find all occurrences" again.
9. You see the "upside down android" icon in the upper left of the "Real Greek" window.
10. Exit and restart And-Bible
11. Repeat steps 2-4 and you'll be asked to "DOWNLOAD" or "CREATE" again.

By the way, this is the most amazing and wonderful app I've ever used. I tell all my friends. This bug is annoying, but doesn't diminish my thankfulness for your work and this app in the least. THANK YOU!

**Comment by kentprimrose** [comment] 2017-11-29 12:45
BTW, this process works just fine with OSHB and StrongsRealHebrew. Search capability in the Hebrew Bible (OSHB) is great.

**Comment by kentprimrose** [comment] 2017-11-29 12:50
One more hint. This seems to work fine with the WHNU (Westcott/Hort) Greek bible, so the problem seems to be the index downloaded or created for MorphGNT. This is survivable, though I miss the accents and breathings that aren't present in WHNU. Still a bug with indexing MorphGNT though.

**Comment by tuomas2** [comment] 2018-11-30 16:06
Step 6 and 9 gave me this (54 matches found):

![screenshot_1543593726](https://user-images.githubusercontent.com/5811789/49300166-2cfab880-f4ca-11e8-8ad2-92fd64c75c0f.png)

So it looks like this is working fine for me. I'm testing with latest beta build in emulator with android 9.
Can you @kentprimrose re-check if this still reproduces for you? 

Please re-open if it does. Closing for now.

**Closed by tuomas2** 2018-11-30 16:06 UTC
Labels: Bug, Prio: Normal
