### ISSUE TITLE
How to view certain verse from external application

### ISSUE THREAD

**Issue by OSDVF** [AndBible/and-bible#822] opened 2020-09-02 15:00 UTC
Hello, I develop an application which features many links to Bible passages and currently I support viewing them only in YouVersion Bible. I'd like to supoort viewing them in And Bible too.
As far as I know, there is no Intent for that purpose defined in And Bible's manifest.
**Is there a way to do it by starting MainBibleActivity directly?**
(I'll try something like that [https://stackoverflow.com/questions/2209513/how-to-start-activity-in-another-application](https://stackoverflow.com/questions/2209513/how-to-start-activity-in-another-application))

**Comment by tuomas2** [comment] 2020-09-02 15:05
There's issue about this, but it's not implemented yet: #64. Should be rather easy to implement.

**Comment by tuomas2** [comment] 2020-09-03 13:39
Duplicate of #64

**Closed as completed by tuomas2** 2020-09-03 13:39 UTC
Labels: Duplicate, Type: Support

**Comment by tuomas2** [comment] 2020-09-03 13:40
Would you let us know what application are you developing?

**Comment by OSDVF** [comment] 2020-09-06 21:15
> Would you let us know what application are you developing?

Suerly. It contains various interactive images and texts (including links to Bible) which are supposed to help people explain the gospel. It isn't published yet.
