### ISSUE TITLE
Multi verse compare returns first verse after hitting back button... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1843] opened 2021-10-12 21:35 UTC
Select two verses, then hit compare from quick menu. Second window correctly displays other Bible books with the two verses compared.  
If you tap on a strong's no in one is the books you are comparing the definition is displayed in the second window.
Now hit the device back button to display the previously compared verses and only the first verse is in the compare window now.

**Comment by agrogers** [comment] 2021-10-12 22:06
I didn't know you could compare two verses! You have taught me a few things
about the app over the last few weeks, Ben.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by bvahedy** [comment] 2021-10-12 23:18
That's why I love AB, There are so many hidden features that it will take a
life time to find all of them😁.

**Comment by tuomas2** [comment] 2021-10-14 07:06
Kind of bug, kind of "by design". This multiple verses comparison is a special case that is not handled so "carefully" and it would be a bit tricky to implement it properly. Also if you compare multiple verses at once and then close app and restore, it does show only 1 verse. Also if you switch workspaces in between, it shows only 1 verse.

I would say that this will remain "'won't fix".

**Closed as completed by tuomas2** 2021-10-14 07:06 UTC
Labels: Type: Bug
