### ISSUE TITLE
Add a simple 'Copy Text' option to the selection popup menu

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1902] opened 2021-10-28 11:24 UTC
It's not possible at the moment to copy the highlighted text only because it always shows the dialog and then includes extra text like '...' and verse reference.

Raised in #1880

**Comment by timbze** [comment] 2021-10-28 14:37
I think this is duplicate of #1371

Though this issue suggests context menu, and 1371 suggests adding feature to share/copy dialog.

**Comment by agrogers** [comment] 2021-10-28 21:55
I like that option. It adds a step but keeps the popup menu shorter. Seems
like #1371 is a good option. I propose closing this one.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by timbze** [comment] 2021-10-28 22:30
@agrogers I agree. Having 2 "copy" items in menu could easily be confusing too. Closing this

**Closed as completed by timbze** 2021-10-28 22:30 UTC
Labels: Type: Feature
