### ISSUE TITLE
Night mode find/history/workspace select 

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#584] opened 2020-03-16 12:40 UTC
**Describe the bug**
Night mode find/history/workspace select are all day mode (white theme) when night mode setting is on

**Bug was found on And Bible version**
Build 350

**Comment by tuomas2** [comment] 2020-03-16 13:20
I can't reproduce, at least in manual night mode.

**Comment by timbze** [comment] 2020-03-16 13:30
For some reason my phone had none of the options selected. I was on manual mode before, but don't know if after latest some updates it got left as nothing or what. After selecting night mode everything works. For some reason the rest of And Bible knew it's night mode, but those few screens did not. Not sure why.

**Comment by tuomas2** [comment] 2020-03-16 15:41
Ah, I see now. We should migrate one shared setting which was changed.

**Comment by tuomas2** [comment] 2020-03-19 11:20
Duplicate of #586 which I just fixed.

**Closed by tuomas2** 2020-03-19 11:20 UTC
Labels: Prio: Major, Type: Bug
