### ISSUE TITLE
Attempting to go to notes from the menu causes the app to  crash

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#697] opened 2020-06-05 02:16 UTC
In build 370 and 371 I noticed when attempting to access Notes from the menu the app crashes.
I am able to create a note by highlighting the verse and tapping on the pencil icon on top menu. 
I'm also able to see the note by tapping on the pencil in the verse and viewing that note. But I'm unable to get a list of notes by going through the main menu ( tap on top left on menu bar then tap on notes)

If you are unable to duplicate this, is it possible that my notes database has been corrupted? If so why would I be able to still create notes.

**Comment by bvahedy** [comment] 2020-06-05 05:33
You are right Timmy, I used sqlIte manager and found one entry in the mynotes table with a chapter 0. Once I removed that and reimported the database I was able to go into notes list from the menu. I will close this ticket.

**Comment by tuomas2** [comment] 2020-06-05 06:19
Although there is illegal chapter 0 in DB I want to fix this such that there's no crash (but missing entries only).

**Comment by tuomas2** [comment] 2020-06-05 06:20
Because #673 might (have) created such illegal entries.

**Comment by tuomas2** [comment] 2020-06-06 07:15
This was fixed in 373 as well.

**Comment by bvahedy** [comment] 2020-06-06 07:23
Since I removed the chapter 0 entry from my notes database manually I would not be able to test this, but since I can still access my notes through the menu it all seems good and no crash so far. I can try to restore an older database and see if I can test it. Will let you know if I find a problem.

**Comment by tuomas2** [comment] 2020-06-06 07:29
You can also edit your database manually to add there chapter 0 entries, to check if this works.

**Comment by bvahedy** [comment] 2020-06-06 07:39
Ok, if there are any notes with a chapter 0 the app doesn't crash and it will display the following window every time you try to go to the my note list:
![Screenshot_20200606-003541_Bible Study](https://user-images.githubusercontent.com/46405809/83939004-33888100-a78e-11ea-9246-5178588b5edc.jpg)

**Comment by tuomas2** [comment] 2020-06-06 08:46
@JJK96 was it like this for tou?

**Comment by JJK96** [comment] 2020-06-06 10:26
Yes, I mentioned this in the pull request, I also mentioned alternatives to this behaviour.

See https://github.com/AndBible/and-bible/pull/699

**Comment by timbze** [comment] 2020-06-06 11:35
I think we need to do database migration and remove notes with chapter 0. That would take care of this error. Why leave non-usable data in database?

**Comment by tuomas2** [comment] 2020-06-06 12:14
that is ok solution to me. just need full table scan for that.

**Comment by tuomas2** [comment] 2020-06-06 13:47
Whoever has time can do this :-) I will do this next week if no pull request appears.

**Comment by tuomas2** [comment] 2020-06-06 15:03
I now implemented data migration in d585d230549086a9972357d7a7ed51d72d24b945. Can someone review the commit?

**Comment by tuomas2** [comment] 2020-06-06 15:07
I think I kind of trigger this chapter 0 bug still in one special case: 

1. Create my note for Gen.1.0 by long-clicking on first title ("Chapter 1"), on KJV. 
 -> there are icon both on both titles as shown in screenshot
2. Click icon on upper title
 -> editor opens chapter 0 note

![Screenshot_1591456008](https://user-images.githubusercontent.com/5811789/83947578-890d6e00-a820-11ea-895a-d74289c021c2.png)

**Comment by timbze** [comment] 2020-06-06 15:37
Should it even be possible to select or make a note for v0? There seems to
be no purpose in it as far as I can tell, we probably should not open
action mode for v0 at all.

I will think on your migration sql a bit more but I think it's the right
way to go.

**Comment by tuomas2** [comment] 2020-06-06 16:06
you are right, it should not.

**Comment by bvahedy** [comment] 2020-06-06 16:20
Can't duplicate, I'm unable to highlight the chapter title only verse one
is selected which is the way it should work. But I'm running beta build 373.

**Comment by timbze** [comment] 2020-06-06 16:32
I had to scroll up as far as possible and then long press above the text as
high as I could and then was able to reproduce it

**Comment by bvahedy** [comment] 2020-06-06 17:54
Ok I tried it with Genesis initial description and I was able to also
duplicate this, but the app no longer crashes which is good.

**Comment by tuomas2** [comment] 2020-06-07 16:47
With the latest fix, I think we can declare this issue fixed. (build 374)

**Comment by bvahedy** [comment] 2020-06-07 20:46
It's still showing me to create a note for verse 0.
If you highlight verse 2 then 1 and then the chapter title. You can then create a note for v0-2 and if you try to go into notes the note will come up empty. But at least no crash happens.  I did this in build 374.

**Closed** 2020-06-08 07:03 UTC
Labels: Prio: Major, Type: Bug

**Comment by tuomas2** [comment] 2020-06-08 08:03
Fixed in build 375 (Thanks @timbze )
