### ISSUE TITLE
Export and share complete study pad / sermon notes

### ISSUE THREAD

**Issue by alan2675** [AndBible/and-bible#1693] opened 2021-09-11 10:51 UTC
It would be very useful to be able to export the complete study pad for notes taken during a sermon.  Exporting to a docx, odt, or pdf would be fine.  Sharing to an app like email, text, or Google Drive would be nice as well.  Thank you!!!

**Comment by tuomas2** [comment] 2021-09-11 11:33
Duplicate of #1328

**Closed as completed by tuomas2** 2021-09-11 11:33 UTC
Labels: Type: Feature
