### ISSUE TITLE
Tiny text rendering issue - not rendering whole page

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1019] opened 2021-05-03 05:32 UTC
When the text is really small so that i can see a whole book on (eg all of Romans) on one screen, only a small part of the book is rendered. If i slowly scroll then additional verses are rendered. If i scroll too quickly then they dont get rendered.

It just seems like you have a hard limit set for the number of verses to render so as to not waste resources. If that is true, perhaps scaling that hard limit inversely based on the font size would solve my problem.

A video here:
https://drive.google.com/file/d/161a_lyUtXuD7cN9MXy9LFDKJqVD33LMH/view?usp=sharing

**Comment by agrogers** [comment] 2021-05-03 07:19
Sorry, i forgot that i had already added an issue for this! It is https://github.com/AndBible/and-bible/issues/1019. These can be merged.

**Comment by tuomas2** [comment] 2021-05-03 08:31
#1019 is actually this issue

**Comment by timbze** [comment] 2021-05-03 12:08
#1006 is similar

**Comment by agrogers** [comment] 2021-05-03 12:20
Yes, sorry! I forgot i had added it via my phone... and added notes to another task.

**Comment by tuomas2** [comment] 2021-05-04 15:55
Duplicate of #1006

**Closed as completed by tuomas2** 2021-05-04 15:55 UTC
Labels: Type: Bug, Prio: Major
