### ISSUE TITLE
Links seem to be duplicating in the Links window

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1533] opened 2021-08-07 11:10 UTC
Happening in the Strongs but I think i saw it elsewhere also.

![image](https://user-images.githubusercontent.com/13920678/128598217-aeb67406-ed92-4723-a038-058693aeb0e3.png)

Ohm yeah, it was here:
![image](https://user-images.githubusercontent.com/13920678/128598242-ed7fd188-8fb1-47ab-bb48-c656f7d27f33.png)

**Comment by tuomas2** [comment] 2021-08-07 13:33
Might be fixed by one of the latest build. Can't reproduce. Please check and re-open if not.

**Closed as completed by tuomas2** 2021-08-07 13:33 UTC
Labels: Type: Bug
