### ISSUE TITLE
Single Word Bookname, find returns chapter 0

### ISSUE THREAD

**Issue by Dob4115** [AndBible/and-bible#2424] opened 2022-12-19 11:43 UTC
I was searching for "Jonah" and when I hit search, I was immediately taken to Jonah chapter 0, not the search results. This happens with "Job" or "Exodus" too. If you search for "Samuel" you are given a list of search results. This seems like a bug to me.

**Comment by tuomas2** [comment] 2022-12-19 12:55
Duplicate of #2423

**Closed as completed by tuomas2** 2022-12-19 12:55 UTC
