### ISSUE TITLE
When in night mode and not full screen minimized windows are not showing... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#307] opened 2019-02-14 23:32 UTC
If night mode is active, all minimized windows disappear from the bottom of the screen.

**Comment by tuomas2** [comment] 2019-02-15 07:14
Can't reproduce. I believe this was fixed in 297.

**Closed by tuomas2** 2019-02-15 07:14 UTC
Labels: Type: Bug

**Comment by bvahedy** [comment] 2019-02-15 16:31
Same thing, this is now working in 297-rc.
