### ISSUE TITLE
App crashes when trying to view footnote during speech...

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#226] opened 2019-01-19 02:49 UTC
During speech if scrolling above the verses that was already read and selecting a verse and then trying to view the footnote for that verse the app crashes.
 This bug is hard to reproduce as the speech is constantly moving the verses as they are read, so  you may have to repeat the above steps multiple times to cause it to occur.
I was however able to capture a logcat and will attach it here.

[logcat.zip](https://github.com/AndBible/and-bible/files/2775072/logcat.zip)

**Comment by tuomas2** [comment] 2019-01-19 06:59
[logcat.txt](https://github.com/AndBible/and-bible/files/2775287/logcat.txt)

**Comment by tuomas2** [comment] 2019-01-19 07:00
Tried to upload txt without zipping and it seems to be OK. So, please upload attachments without zipping if possible to make opening easier. 

Crash is easy to fix because of logcat report. I guess the expected behavior is that nothing happens and activity mode is closed if we are no longer in selected passage?

**Comment by tuomas2** [comment] 2019-01-19 07:30
Fixed in a6c4a7e

**Closed by tuomas2** 2019-01-19 07:30 UTC
Labels: Affects: Beta, Bug
