### ISSUE TITLE
Seek other storage devices for books

### ISSUE THREAD

**Issue by ildar** [AndBible/and-bible#144] opened 2018-08-17 06:32 UTC
Currently And-Bible uses
* Android/data/net.bible.android.activity/
* jSword

folders on /sdcard. Times are running fast and it's now reasonable to care about other storage devices: not just external MMC but also USB/network/whatnot filesystems.

Also with rising target SDK it's required to *ask* storage permission from user.

**Comment by tuomas2** [comment] 2018-08-17 07:11
I'm aware of this issu and I'll handle this.
This is the last TODO entry on my SDK update ticket :) 
https://github.com/mjdenham/and-bible/pull/143

**Comment by ildar** [comment] 2018-08-18 14:11
Nope, sorry.
1. It should ask the permission *before* asking to download Bible books on
the *first start*. It doesn't, I just checked.
2. Actually this FR was on different topic: use books on secondary storage.
I just checked: the new apk doesn't see jSword folder on secondary sdcard.

сб, 18 авг. 2018 г., 16:20 Tuomas Airaksinen <notifications@github.com>:

> Fixed this in latest APK, see #140
> <https://github.com/mjdenham/and-bible/pull/140>
>

**Comment by tuomas2** [comment] 2018-08-18 14:35
Hi @ildar 
1. to download to Android/data/net.bible.android.activity/ does not require any permissions. If there's a bug however please let me know.

On the other hand, to use /sdcard/jsword does (as well as backup/restore bookmarks feature, which also asks permission). I implemented permission query for /sdcard/jsword which is now done at app startup. 

2. That's true. So the second part was more like feature request, not a bug. I was not planning to cover that in my fix. I'm not sure how useful it is to support custom bible folders. If you ask me we could consider dropping support for /sdcard/jsword and suppoort only Android/data/net.bible.android.activity/.

**Comment by ildar** [comment] 2018-08-18 16:09
I neither like multiplication of 2nd level folders (/sdcard/something). So
moving jSword somewhere might be a good idea.

But `Android/data/net.bible.android.activity` definitely is not the place.
The reason is dead simple: it is removed on the app removal.

On FR it's ok just to leave it open.

**Comment by mjdenham** [comment] 2018-08-18 20:14
Where would you like to put the manual install folder Ildar?

**Comment by ildar** [comment] 2018-08-19 07:17
Google seems got determined about what folders should be in root of sdcard.
So `$SDCARD/Documents/jSword` seems to be a good place.

**Comment by timbze** [comment] 2021-04-11 20:39
With Android only becoming stricter about apps accessing storage I think we should close this in favor of #632. 
Will let @tuomas2 decide

**Comment by tuomas2** [comment] 2021-04-12 08:16
I have disabled option to use jsword folder for Android 10+ devices as it does not work anyway. I agree that this can be closed, and #632 can be implemented at some point.

**Closed by tuomas2** 2021-04-12 08:16 UTC
Labels: Status: Preliminary, Type: Feature
