### ISSUE TITLE
Shortening a previously made bookmark

### ISSUE THREAD

**Issue by Dleemuse** [AndBible/and-bible#1794] opened 2021-10-03 15:39 UTC
Is it possible to shorten a previously made bookmark by a verse(s), without having to delete the bookmark & starting over? 

For example, I previously bookmarked Ps. 106:7-11, but want to shorten this particular bookmark to just Ps. 106:9.

Thanks, 

Debra

**Comment by bvahedy** [comment] 2021-10-03 15:56
Not to my knowledge. We figured your "yes"  should be a yes and you "no"  should be a no😂 so you can't change your mind once you set the bookmark. Unless you have notes attached to the bookmark it just takes couple of taps to set the new bookmark and delete the old one. You can tap over the already bookmarked verse and assign it the same lable as the one you want to delete. Then just tap on the other verse that has the bookmark and delete it.

**Comment by Dleemuse** [comment] 2021-10-03 16:53
Lol, very funny, you know women, we reserve the prerogative to change our minds. Yeah, I just went ahead & made a new one & deleted the old.

Thank you Ben.

Debra

**Comment by bvahedy** [comment] 2021-10-03 17:10
Btw, I made this ticket a feature request in case Toumas decides it's worth implementing.

**Comment by timbze** [comment] 2021-10-03 18:21
#1079 was made to try and implement this but there was some issue that needs to still be figured out

**Comment by timbze** [comment] 2021-10-03 18:22
This is actually a duplicate of #1078

**Closed as completed** 2021-10-03 18:22 UTC
Labels: Type: Feature, Type: Discussion

**Comment by agrogers** [comment] 2021-10-04 06:01
I believe it is on Tuomas' list to do. He wants the feature.
