### ISSUE TITLE
Hide window overlay hamburger menu button 

### ISSUE THREAD

**Issue by NotSoImportant** [AndBible/and-bible#321] opened 2019-02-19 22:50 UTC
This button is like a quick access to do window related actions. Hower it is very disturbing while reading.
So please remove it, make it configurable, or at least hide it in full screen.
Its not helpful that it hides after ~1sec (in full screen), because on scrolling it reappears. 
Thank you!

**Comment by tuomas2** [comment] 2019-02-19 23:21
This is duplicate of #299 and this will be implemented one way or another in #299. Moving your comment there.

**Closed by tuomas2** 2019-02-19 23:21 UTC
