### ISSUE TITLE
Export and share Notes and Bookmarks.

### ISSUE THREAD

**Issue by treestryder** [AndBible/and-bible#61] opened 2016-10-02 18:01 UTC
It would be nice to be able to export and/or share Notes and lists of bookmarks.

**Comment by timbze** [comment] 2019-07-28 21:51
@tuomas2 I'm suggesting to close this issue as duplicate of #188 and #189. Those issues have discussion about this same subject.

**Comment by tuomas2** [comment] 2019-07-29 07:08
Duplicate (#188, 189)

**Closed by tuomas2** 2019-07-29 07:08 UTC
Labels: Prio: High, Type: Feature, Work amount: Moderate
