### ISSUE TITLE
Provide row-major ordering for the Choose Chapter grid, and the Choose Verse grid

### ISSUE THREAD

**Issue by uniqueid001** [AndBible/and-bible#1213] opened 2021-06-30 21:08 UTC
#1122 added a user-controlled setting for ordering the Bible book chooser in row-major order, however it leaves the chapter and verse grids in column-major order.  I would like to apply row-major order to the chapter, and verse, selection grids.

_Design questions:_  

1. Should each of the three choosers have a separate preference?  I think this is excessive: I expect that others who want row-major order in one of the choosers will also want it in all three.
2. If there is only a single preference, should the chapter and verse activities also provide a menu item for toggling it?

**Comment by timbze** [comment] 2021-07-01 00:15
1. I think you're right
2. I think that would be excessive as well, if it's in book chooser activity I believe that's good

Also duplicate of #1208

**Closed as completed** 2021-07-01 07:16 UTC
Labels: Type: Feature, Prio: Minor, Status: Preliminary

**Comment by uniqueid001** [comment] 2021-07-01 13:04
> Also duplicate of #1208

Thanks!  Sorry for creating a duplicate; I hadn't seen that report.
