### ISSUE TITLE
Automated Backup

### ISSUE THREAD

**Issue by shompoe** [AndBible/and-bible#974] opened 2021-04-15 17:45 UTC
If I make extensive use of notes and bookmarks in my studies then I will be concerned about loosing all of that information if something were to happen to my phone. Or even, for example, if the app started to crash and I neeses to delete app data to fix it.

My suggestion is automated backup of the application database to the filesystem. Perhaps each time the app is started. Then it would be the user's responsibility if he/she wanted to implement automatic synchronization of those backup files to a cloud provider or something else.

I have considered just taking manual backups but it seems cumbersome to have to remember each time I make a new bookmark or edit a note.

**Comment by tuomas2** [comment] 2021-04-16 07:07
Duplicate of #370

**Closed as completed by tuomas2** 2021-04-16 07:07 UTC
Labels: Type: Feature, Prio: Minor, Status: Preliminary
