### ISSUE TITLE
Create search index / find dialog buttons missing

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#811] opened 2020-08-08 23:30 UTC
The "Cancel" and "Create" buttons are invisible on "Create index" dialog on small screen with big-ish text. See screenshot:
![Screenshot_20200808-210616](https://user-images.githubusercontent.com/35117769/89721592-b8656600-d99c-11ea-9dc6-5d7f3384e02f.png)

Device info:
And Bible version: 3.3.388#build-387-test-4-g608e69775 (built 23/07/20 19:54:57)
Android version: 8.0.0
Android SDK version: 26
Manufacturer: motorola
Model: Moto Z2 Play

Storage Mb free: 26694

Used heap memory in Mb: 14
Max heap memory in Mb: 192

https://support.andbible.org/scp/tickets.php?id=53

**Comment by tuomas2** [comment] 2020-08-12 07:58
I guess also "Find" button missing falls into same category:

https://support.andbible.org/scp/tickets.php?id=54

**Comment by tuomas2** [comment] 2020-08-12 13:23
![Screenshot_20200812-091711_Bible Study](https://user-images.githubusercontent.com/5811789/90020161-24570f80-dcb8-11ea-85ec-d03782e6a989.jpg)

**Comment by tuomas2** [comment] 2020-08-20 08:39
The problem is that search.xml and search_index.xml are AlertDialog-like custom activities. Need to add some scroll views.

**Comment by tuomas2** [comment] 2020-08-20 09:22
I'm restoring search-related activities (all but search results) to normal style (not alertdialog style). Now it works also with very large dpis.
Improved also soft input to have search button.  

![Screenshot_1597915261](https://user-images.githubusercontent.com/5811789/90752219-c9d53900-e2df-11ea-8d05-f27122dca6e6.png)

**Comment by tuomas2** [comment] 2020-08-20 09:22
Will be fixed in build 389

**Closed as completed by tuomas2** 2020-08-20 09:22 UTC
Labels: Type: Bug, Prio: Major

**Comment by bvahedy** [comment] 2020-08-21 19:15
Verified fix in 389 beta build.
