### ISSUE TITLE
Crash: lateinit property documentItemAdapter has not been initialized

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3150] opened 2024-01-04 10:33 UTC
https://support.andbible.org/scp/tickets.php?id=2375

```
Device info:
App id: net.bible.android.activity
Version: 5.0.793#b51bd8bee googleplay standard release (built 28/12/23 11:09:28)
Android version: 9
Android SDK version: 28
Manufacturer: Amazon
Model: KFONWI
Storage Mb free: 46095
WebView version: 116.amazon-webview-v116-5845-tablet.5845.229.65
SQLITE version: 3.42.0
Used heap memory in Mb: 3
Max heap memory in Mb: 128

Exception:
kotlin.UninitializedPropertyAccessException: lateinit property documentItemAdapter has not been initialized
at net.bible.android.view.activity.base.DocumentSelectionBase.getDocumentItemAdapter(DocumentSelectionBase.kt:123)
at net.bible.android.view.activity.base.DocumentSelectionBase$populateMasterDocumentList$2.invokeSuspend(DocumentSelectionBase.kt:385)
at net.bible.android.view.activity.base.DocumentSelectionBase$populateMasterDocumentList$2.invoke(DocumentSelectionBase.kt:0)
at net.bible.android.view.activity.base.DocumentSelectionBase$populateMasterDocumentList$2.invoke(DocumentSelectionBase.kt:0)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
at net.bible.android.view.activity.base.DocumentSelectionBase.populateMasterDocumentList(DocumentSelectionBase.kt:381)
at net.bible.android.view.activity.download.DownloadActivity.access$populateMasterDocumentList(DownloadActivity.kt:88)
at net.bible.android.view.activity.download.DownloadActivity$onOptionsItemSelected$2.invokeSuspend(DownloadActivity.kt:500)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:256)
at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:191)
at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:163)
at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1406)
at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:320)
at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:297)
at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
at kotlinx.coroutines.JobSupport.makeCompleting$kotlinx_coroutines_core(JobSupport.kt:810)
at kotlinx.coroutines.CompletableDeferredImpl.complete(CompletableDeferred.kt:90)
at net.bible.android.view.activity.base.ActivityBase.onActivityResult(ActivityBase.kt:355)
at net.bible.android.view.activity.download.DownloadActivity.onActivityResult(DownloadActivity.kt:447)
at android.app.Activity.dispatchActivityResult(Activity.java:7515)
at android.app.ActivityThread.deliverResults(ActivityThread.java:4431)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:4480)
at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:211)
at android.app.ActivityThread.main(ActivityThread.java:6775)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@632c053, Dispatchers.Main.immediate]
```

**Comment by timbze** [comment] 2024-01-12 12:04
Duplicate of #3098

**Closed as completed by timbze** 2024-01-12 12:04 UTC
Labels: Type: Bug, Affects: Alpha
