### ISSUE TITLE
Crash: documentItemAdapter has not been initialized

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3161] opened 2024-01-09 18:14 UTC
https://support.andbible.org/scp/tickets.php?id=2380

```
Geräteinfo:
App id: [net.bible.android](https://net.bible.android/).activity
Version: 5.0.793#b51a161d1 fdroid standard release (built 31/12/24 13:06:16)
Android version: 13
Android SDK version: 33
Manufacturer: Fairphone
Model: FP4
Storage Mb free: 94346
WebView version: 114.0.5735.60
SQLITE version: 3.42.0
Used heap memory in Mb: 4
Max heap memory in Mb: 256

Exception:
kotlin.UninitializedPropertyAccessException: lateinit property documentItemAdapter has not been initialized
at [net.bible.android](https://net.bible.android/).view.activity.base.DocumentSelectionBase.getDocumentItemAdapter(DocumentSelectionBase.kt:123)
at [net.bible.android](https://net.bible.android/).view.activity.base.DocumentSelectionBase$populateMasterDocumentList$2.invokeSuspend(DocumentSelectionBase.kt:385)
at [net.bible.android](https://net.bible.android/).view.activity.base.DocumentSelectionBase$populateMasterDocumentList$2.invoke(DocumentSelectionBase.kt:0)
at [net.bible.android](https://net.bible.android/).view.activity.base.DocumentSelectionBase$populateMasterDocumentList$2.invoke(DocumentSelectionBase.kt:0)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
at [net.bible.android](https://net.bible.android/).view.activity.base.DocumentSelectionBase.populateMasterDocumentList(DocumentSelectionBase.kt:381)
at [net.bible.android.view.activity.download](https://net.bible.android.view.activity.download/).DownloadActivity.access$populateMasterDocumentList(DownloadActivity.kt:88)
at [net.bible.android.view.activity.download](https://net.bible.android.view.activity.download/).DownloadActivity$onCreate$4$1.invokeSuspend(DownloadActivity.kt:212)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:256)
at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:191)
at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:163)
```

**Comment by timbze** [comment] 2024-01-12 12:04
Duplicate of #3098

**Closed as completed by timbze** 2024-01-12 12:04 UTC
Labels: Type: Bug, Affects: Alpha
