### ISSUE TITLE
On Android 6 the link window after first use displays previous definition. 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#2009] opened 2021-12-29 03:23 UTC
From ticket:
https://support.andbible.org/scp/tickets.php?id=1167
And
https://support.andbible.org/scp/tickets.php?id=1162

1 in "Application preferences", i have the "Links window" set

2 In "All Text Options" I have Strongs numbers  set to "Text and Links"

3 I have the Strongs in the numbers mode not the dots mode

4 When i first use the app I click on a Strongs number and it shows in a separate links window the correct number  i choose another Strongs number and it switches to that new number i can keep doing this without a problem, so  it works like it should

5 But once i close that linked window and go back to clicking on a Strongs number and it opens a new link window it shows the very last Strongs number i clicked in the previous session (the window i just closed) its like it won't refresh the new window no matter how many Strongs numbers i click it stays on that same number

6 Now i can go back to "Application preferences", and turn off the "Links window" setting then it works fine by giving me a whole new window but i have to toggle back and forth between windows instead of both on the same screen with 2 separate windows.

**Comment by tuomas2** [comment] 2021-12-30 07:09
Duplicate of #2013

**Closed as completed by tuomas2** 2021-12-30 07:09 UTC
Labels: Type: Bug
