### ISSUE TITLE
Two window scrolling

### ISSUE THREAD

**Issue by tse-gratis** [AndBible/and-bible#1879] opened 2021-10-22 19:50 UTC
When multiple windows are open quick scrolling to verses can jerk, and sometimes go in the opposite direction, slow down, or jump to a new position after scrolling has finished, or begin scrolling both up and down after user scrolling interaction has finished 

Happens in version 4.0. Didn't happen in the previous version

To most easily reproduce, try quickly scrolling the lower 'pane' aka 'window' up and down. Happens frequently to me with all panes, but finding a consistent set of flicks to reproduce it in the same way is hard -- it needs to be those flick scrolls with velocity, and more easily happens with 3 or more panes

Also when scrolling, bookmark pane accidentally pops up at the place where i tapped -- i dont personal use the cute bookmark pop up pane, i normally greatly benefit from the multilingual language panes 'windows' open at a time. So often have many of these

When trying to find a set of flick scrolls, followed by tap, to stop the last velocity scroll, i seem to of crashed the app. Auto-scroll stopped working, and then the interface more generally, tho bookmark pop ups continued to work, a few minutes later the app stopped delivering visual updates, and crashed

Thanks so much

**Comment by agrogers** [comment] 2021-10-23 09:48
Hi

I had never really noticed that before but it does do some weird things for
me too when I scroll quickly using a fling.

What seems to be happening is that although I am flinging the top window it
is the bottom window that is determining which verse to show. And because
the bottom window lags behind the top window the top window goes in reverse
to sync with the bottom window.

Sometimes both windows bounce up and down which makes me think that they
are both alternating taking over the sync priority.

The solution to this issue would be to ensure that only the active window
sets the current verse and all other windows must follow it.

But I'm just guessing here - could be something entirely different.

**Comment by bvahedy** [comment] 2021-10-23 16:49
No, this is a feature this was implemented a year or so ago. If the bottom
window is displaying a larger size data so that as you move up on the
bottom window we didn't want the top window to jump to the next verse so
that the user can still see the top window verse and still be in sync with
the bottom.
This comes in handy when viewing modules like HiSB in the bottom window and
scrolling to the later portion of the verse without having to lose the
context on the top window.
We should not change this feature.

**Comment by agrogers** [comment] 2021-10-23 20:00
I didn't test it with the bottom window. I was just flinging the top
window. And it was the top window that I was flinging that actually started
moving in the **opposite direction** to which I flung it. It was like the
window that I **wasn't** moving was controlling the window I was moving.
That doesn't seem right to me.

Are you sure we are talking about the same thing?

**Comment by agrogers** [comment] 2021-10-23 20:07
[EDITED and removed incorrect info]
The original poster's complaint I think is that fast scrolling is now quite difficult. I don't scroll like that much. But I tend to agree with him.

**Comment by agrogers** [comment] 2021-10-23 20:21
Also reported by another user: 

Hi,  

Thanks for the update for the bible app, I've been using this app for many years and really appreciate your effort.  May God bless your work. 

After the recent update I've been having problem with scrolling the page,  whenever I scroll up it always roll back,  so it's kind of disturbing  Hope you can have a look,  thanks. 


Evelyn

**Comment by bvahedy** [comment] 2021-10-23 20:27
Ok, I see the bug you described with an image only happens when you are flinging down which means you are moving backward on the page, for me this only happens when you reach Genesis where verse one on top window doesn't match the bottom window. I can't duplicate it with any other book.
Also, I can duplicate, every once in a while the backward scroll of top window realigning, but in all cases both windows are in sync in the end. I don't see a problem there.

**Comment by tse-gratis** [comment] 2021-10-23 20:55
I find it to be a hard bug to reproduce, even it happens to me with frequency

Try opening a bunch of windows, and flip up and down in one, then (not essential, but makes the problem clearer), tap the same window to stop the velocity scrolling. (tap without velocity scrolling brings up bookmark dialog)

The previous behavior is that that window will stop, and other windows will either jump into, or ease into the same position

However, when i updated there were several unexpected possible effects after the single tap, that stops the scroll. So after the tap, with no user interaction, the tapped window will begin to do one of:
* scroll both up and down
* jump to an unexpected location a few moments later
* judder or move slowly on its own accord

When trying to diagnose this further im afraid the app began crashing on me

Thanks

I don't know, maybe the window sync easing completes after or before the velocity scroll completes??

Samsung, Android version 11

**Comment by agrogers** [comment] 2021-10-23 21:10
I can reproduce the window jitter pretty much every time. See

https://drive.google.com/file/d/1M2NOsY6tzTKyKbP1xNIu7_x704LaW6_z/view?usp=drivesdk

**Comment by bvahedy** [comment] 2021-10-24 00:18
With multiple windows, after speed scrolling and stopping the scroll, some of the windows do scroll up or down until they all sync to the top window. But I don't see any issues with that.

**Comment by agrogers** [comment] 2021-10-24 00:59
But they aren't syncing to the active window (the one I am scrolling)
because that one scrolls backward which I don't think should ever happen.

**Comment by bvahedy** [comment] 2021-10-24 02:38
@agrogers I agree the scroll backward to Genesis 1 will always end up with the lower window being on verse 4. We should open a bug ticket for that, but that only happens when you reach the first book and the app fails to sync the lower windows. It's a minor bug, nonetheless it should be recorded and fixed as time permits.

**Comment by agrogers** [comment] 2021-10-24 03:20
I think we are talking about two different things 🙄 I agree that the
Genesis 1 issue is a minor bug.

It's the weird scrolling backwards in a window in which I am trying to
scroll forwards that the other users have raised that I think is a more
serious issue. It makes fast scrolling very clumsy. You saw that in the
video?

**Comment by bvahedy** [comment] 2021-10-24 05:11
I saw the video, but in the end both windows are synced correctly. I don't think anyone is going to read the screen while it's scrolling that fast. It may be distracting but when everything stops moving it all seems well.

**Comment by agrogers** [comment] 2021-10-24 06:37
Ah yes, we were focusing on two different things. My fault for bringing up
Genesis 1 - it always generates some disagreement ;-)

This issue I believe is about the scrolling issue not the final verse
issue. And related to that is that it doesn't stop at the verse I want it
to stop at but stops suddenly and sometimes scrolls backwards when it
should slowly come to a stop on the active window verse.

**Comment by tuomas2** [comment] 2021-10-28 08:31
Also here summarized bug report after long discussion would be nice. @agrogers and @bvahedy should know how to do :-)

**Comment by agrogers** [comment] 2021-10-28 12:35
😊 Summary : The active window which is being flung quickly in one
direction will actually stop suddenly and reverse direction when a second
synced windows open. It seems to be because it is taking its verse
reference to sync from the non-active which I don't think it should do.

In brief - The active window should not reverse direction when it being
flung. See video above

**Comment by reckel-jm** [comment] 2021-11-18 13:56
Hello, I can confirm the same bug since the upgrade of version 4. I made a screencast video to reproduce the bug: https://youtu.be/oeRgKiyQ2HU

**Comment by agrogers** [comment] 2021-11-19 05:05
Yeah, that is what I see as well. Tuomas, do you agree this is a bug? Or a
feature?

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment] 2021-11-19 07:31
I'll check. Either bug or annoying feature I guess.

**Comment by tuomas2** [comment] 2021-12-02 10:13
> When I try to scroll it drifts backwards. This seems to happen on my laptop using BlueStacks but I haven't noticed it happen yet on my cell phone. I don't know but my guesses are it might have to do with the parallel translations or maybe the link Strong's definitions or morphological codes.

https://support.andbible.org/scp/tickets.php?id=1084

**Comment by tuomas2** [comment] 2021-12-16 08:35
Re-opening this, as I had to revert the fix due to more severe #1977

**Comment by tuomas2** [comment] 2021-12-16 08:37
We need to separate "current verse" indicator from sync code, to avoid #1977. Thus it is probably necessary to add debouncing to sync code in android side.

> Debouncing on Android side:
> https://gist.github.com/Terenfear/a84863be501d3399889455f391eeefe5
> https://stackoverflow.com/questions/50858684/kotlin-android-debounce

**Closed as completed** 2021-12-16 09:20 UTC
Labels: Type: Bug
