### ISSUE TITLE
Share / export selection of bookmarks

### ISSUE THREAD

**Issue by mzealey** [AndBible/and-bible#455] opened 2019-12-01 15:09 UTC
**Is your feature request related to a problem? Please describe.**

I frequently preach or translate sermons. It would be great if I could create a list of verses in the bible similarly to bookmarks but for a specific event and in a specific order (drag to reorder or somesuch). Then if I am preaching to share eg via whatsapp or so with some sort of link (I just a fake url with a list of verse refs in some standard format) which other people can then use for translation. Probably like the 'set list' feature in https://songs.worshipleaderapp.com/

**Describe alternatives you've considered**

Bookmarks with tags have similar functionality but no ability to order or share

**Comment by tuomas2** [comment] 2019-12-01 18:46
It might be feasible to implement share functionality to bookmark tags / bookmark selections.

**Comment by timbze** [comment] 2019-12-08 01:52
Similar to #189. Additional idea here is to be able to order verses to share.

**Comment by mmm4m5m** [comment] 2020-02-08 07:30
I would be glad to see this feature (or #189, or similar).
I would like to synchronize bookmarks between tablet and phone.

Thanks!

**Comment by timbze** [comment] 2022-08-05 23:17
Closing as duplicate of #189

**Closed by timbze** 2022-08-05 23:17 UTC
Labels: Type: Feature, Prio: Minor, Bookmarks, Status: Preliminary
