### ISSUE TITLE
Find all occurrences fails to synchronize all windows to the verse... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#488] opened 2020-01-01 01:49 UTC
When doing a strong look up on a word and tapping on find all occurrences. Select a verse from the search and with three windows open the top and sometimes the bottom windows are off by a verse. 
![Screenshot_20191231-174740_And Bible](https://user-images.githubusercontent.com/46405809/71637352-e65c1e00-2bf5-11ea-8379-1f38acd5a8fe.jpg)

**Comment by tuomas2** [comment] 2020-01-01 08:34
I was trying this with WEB and FinRK on top & bottom, and ESV in the middle,
and could not reproduce yet. 

Need to have "open links in a new window" option set off.

I'm thinking if this could be something to do with versifications. 
Can you confirm if this is a new bug or if you have experienced the same thing earlier too?

**Comment by bvahedy** [comment] 2020-01-01 22:32
I believe this is a new bug, I do this often and this did not used to
happen in the past leases.

**Comment by tuomas2** [comment] 2020-01-02 06:45
I think this is probably fully reproducible if you give me exact steps (including module names, verse in which I need to click strongs link which, and result which I need to select from search all occurrences). So could you give me more details for this.

**Comment by bvahedy** [comment] 2020-01-02 18:37
Navigate to Psalms 16:11

Top window JPS
Middle window HISB
Bottom window WLC

Tap on strong's no. 5331 the last word in the verse, "Nesakh".

The middle window will show the dict. From here tap on the find all .

Select the first item which is 1Sam 15:29

The top and bottom window show v30 and the middle window shows v29.

This doesn't happen with the other verses in the search list.

**Comment by tuomas2** [comment] 2020-01-02 18:49
![Screenshot_20200102-204924](https://user-images.githubusercontent.com/5811789/71685579-6d012e80-2da1-11ea-943a-9061a6f38d53.png)

**Comment by bvahedy** [comment] 2020-01-02 21:19
Can you turn on one verse per line and try again.

**Comment by bvahedy** [comment] 2020-01-02 22:24
I just tried this with a fresh build of 333 and it is still happening. It
could be related to one verse per line setting.

**Comment by tuomas2** [comment] 2020-01-03 06:02
![Screenshot_20200103-080210](https://user-images.githubusercontent.com/5811789/71709383-6e614400-2dff-11ea-81bd-3b848097c522.png)

**Comment by tuomas2** [comment] 2020-01-03 06:04
Can it be that it is related to your custom CSS then? Can you try to turn it off and see if it happens still (disable access to sd card)?

**Comment by bvahedy** [comment] 2020-01-03 06:43
Here is the logcat file, hope you can figure out from the attached log as to why it happens to me and not you. 
[logcat.zip](https://github.com/AndBible/and-bible/files/4018288/logcat.zip)

**Comment by bvahedy** [comment] 2020-01-03 06:46
This is the screen result:
![Screenshot_20200102-224519_And Bible](https://user-images.githubusercontent.com/46405809/71710558-b0fc2f80-2db1-11ea-8255-4aaf5a75b82f.jpg)

**Comment by bvahedy** [comment] 2020-01-03 15:42
Ok, I turned off the CSS file access and it seems to be working, but why is this happening now? I have used CSS for a long time and this issue didn't exist before.

**Comment by tuomas2** [comment] 2020-01-03 16:52
Give me (again) your CSS bundle and I'll investigate.

**Comment by bvahedy** [comment] 2020-01-03 16:57
Unzip and place/replace the jsword dirctory file structure with this one
because it has also the fonts I use:

https://1drv.ms/u/s!AgQrBUWnj0-jhT1WqR0OPdGjk3RJ

Thanks for looking into it.

Happy New year!

**Comment by tuomas2** [comment] 2020-01-09 09:13
Will be fixed > 334

**Comment by bvahedy** [comment] 2020-01-11 03:23
I'm still experiencing this in build 336.

**Comment by tuomas2** [comment] 2020-01-11 21:06
I want to fix this properly

**Comment by tuomas2** [comment] 2020-01-13 08:53
This might be fixed in > 336. Please let me know if *any* incident of this take place.

**Comment by bvahedy** [comment] 2020-01-13 19:16
It's still broken. Also when I select Job 4:20 from the search list the book ref. says 4:21 in the title menu but the winds are on 4:20. See pics. 
![Screenshot_20200113-110715_And Bible](https://user-images.githubusercontent.com/46405809/72284512-fe6c6e00-35f5-11ea-8886-4a7fe5495eff.jpg)
![Screenshot_20200113-111241_And Bible](https://user-images.githubusercontent.com/46405809/72284530-0d532080-35f6-11ea-826e-3d175ad23940.jpg)

**Comment by tuomas2** [comment] 2021-08-04 10:03
I believe we haven't fixed this still. How is it @bvahedy ?

**Comment by agrogers** [comment] 2021-08-04 12:12
I can't recall seeing it for weeks at least.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by bvahedy** [comment] 2021-08-04 16:57
This seems to be working now, can't dupplicate it.

**Closed** 2021-08-04 16:57 UTC
Labels: Prio: Major, Type: Bug
