### ISSUE TITLE
Bookmark colors not consistent for individual bookmarks

### ISSUE THREAD

**Issue by Dleemuse** [AndBible/and-bible#1386] opened 2021-07-23 14:36 UTC
I have said several times that I am tech challenged, so I am sure this is my issue not yours.

When I am for example, making 2 (or more) underlined bookmarks with overlapping verses, the color of each individual bookmark does not stay consistent. On the overlapping verse(s) where I do have more than 1 underline, they are both the same color instead of 2 different colors. If using more than 1 underlined colored bookmark, how do I get it to show the colors assigned to each individual bookmark & not be all the same color? 

Thanks! 

![Screenshot_20210723-073315_Bible Study](https://user-images.githubusercontent.com/83124765/126797886-589b07ea-4fea-431a-b2b1-a41acec0ec22.jpg)
![Screenshot_20210723-073304_Bible Study](https://user-images.githubusercontent.com/83124765/126797891-55f4b06a-68b0-4e15-99c2-441136396208.jpg)

**Comment by timbze** [comment] 2021-07-23 14:40
This does seem like a bug. Thanks for reporting it. I was able to reproduce the issue

**Comment by Dleemuse** [comment] 2021-07-23 14:43
Thank you, with me you never know, could be something simple & I just don't know it :)

**Comment by tuomas2** [comment] 2021-07-23 14:43
No @timbze  we can show only 1 underline (it is the case also when there's "double"-style), and double-styled underline are just mark that there are 2 or more bookmarks under it. Colors can't be controlled individually with css.

**Comment by agrogers** [comment] 2021-07-23 14:55
Hi Debra

What i think you want is this: https://github.com/AndBible/and-bible/issues/1017#issuecomment-845740097 
But as Tuomas said, doing different coloured underlines is actually pretty hard. So the best we can do is indicate that there is more than one bookmark by showing two lines.

However, perhaps that is a bit misleading. A person has two bookmarks and can see two lines but one of the lines is the wrong color. Perhaps we should not use the double underline.

Here is an alternative...
![image](https://user-images.githubusercontent.com/13920678/126800454-addfc24b-3733-4683-b4cb-4df5e5bb88ff.png)

**Comment by Dleemuse** [comment] 2021-07-23 15:03
OK, thanks Tuomas. It does make it a lot harder to see at a glance when there are multiple bookmarks which verses belong to which bookmarks, see the following for example. On these verses I have a total of 5 bookmarks, 1 of which has a different color (which does not show up).

Also, at a glance, I can not tell that I have 5 bookmarks here until I click the verse(s). It would be nice to see how many I dividual bookmarks at a glance (though having said that, it might get crowded with so many underlines) & also for the color to be consistent when you have more than 1 underline. Here I am wishing for thing that I don't even know whether they are possible or not :)

Thank you everyone for all of your hard work improving what was already the best Bible app out there!

Debra

**Comment by Dleemuse** [comment] 2021-07-23 15:04
![Screenshot_20210723-095556_Bible Study](https://user-images.githubusercontent.com/83124765/126801679-6d367423-d0e8-4cdd-b159-0e36f53ca0cf.jpg)
![Screenshot_20210723-095605_Bible Study](https://user-images.githubusercontent.com/83124765/126801682-7c8c65c4-ed3c-40e8-abb0-49a8a698f18d.jpg)

**Comment by timbze** [comment] 2021-07-23 15:06
> No @timbze we can show only 1 underline (it is the case also when there's "double"-style), and double-styled underline are just mark that there are 2 or more bookmarks under it. Colors can't be controlled individually with css.

Ok, thanks for the explanation

**Comment by agrogers** [comment] 2021-07-23 15:10
What I sometimes do is use the normal background colour highlight if i really want to see multiple bookmarks. If you do that you can show as many colours as you like plus one underline color.
![image](https://user-images.githubusercontent.com/13920678/126802275-69553077-a694-48aa-b0c3-9ddc6e268a36.png)

The underline was intended for more subtle highlighting. The background color for more dominant highlighting. I prefer the underline approach for whole verses but sometimes I need to use the background to get the effect i want.

**Comment by agrogers** [comment] 2021-07-23 15:11
Oh, you choose how you want to highlight in the label setup area.

**Comment by Dleemuse** [comment] 2021-07-23 15:16
Thank you, this helps!

**Comment by timbze** [comment] 2021-07-23 15:30
@Dleemuse also, I think you know this, but you can also add bookmarks to just parts of a verse, or just a word by long-pressing on the verse and then highlighting whichever portion you wish to add the bookmark to. Then click "Bookmark" in the popup menu, and then "Selection".

Another note, the "bookmark" icon in front of your label shows which label is primary on your bookmark. See my red circle for your bookmark here:
![image](https://user-images.githubusercontent.com/35117769/126804990-16d6948f-6c35-4f18-880e-360cfbf39854.png)

When you open the bookmark by tapping it, and then tapping the label area at the top, you will get the window with recent labels etc, if you tap the "Judging" label the icon will jump to that one, making that the primary label. That way (with primary label) you can configure which color will show on the verse when you have multiple labels on 1 bookmark.

**Comment by tuomas2** [comment] 2021-07-23 18:26
@agrogers I don't like how this would look like. Will keep it in double-style rather. 

![Screenshot_20210723_212543](https://user-images.githubusercontent.com/5811789/126825473-c6893e0e-12c2-49d1-bdc1-8dcc625a7785.png)

**Comment by agrogers** [comment] 2021-07-24 10:53
I think the wavy line could have been good if it wasn't breaking for spaces
and lower parts of the letters. But I agree its not  beautiful as it is.

I just had a look at the code and have made a pull request that does
'proper' two color underlines:
https://github.com/AndBible/and-bible/pull/1397

I haven't tested it well but so far so good.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by Dleemuse** [comment] 2021-07-25 02:41
Yes, I just figured out recently what changing the priority bookmark does. Thanks
Debra

Sent from Yahoo Mail on Android 
 
  On Sat, Jul 24, 2021 at 5:53 AM, Andrew ***@***.***> wrote:   

I think the wavy line could have been good if it wasn't breaking for spaces
and lower parts of the letters. But I agree its not beautiful as it is.

I just had a look at the code and have made a pull request that does
'proper' two color underlines:
https://github.com/AndBible/and-bible/pull/1397

I haven't tested it well but so far so good.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by Dleemuse** [comment] 2021-07-25 02:43
Agreed, wavy Line does not look good. 
Debra

Sent from Yahoo Mail on Android 
 
  On Sat, Jul 24, 2021 at 9:41 PM, Dlee ***@***.***> wrote:   Yes, I just figured out recently what changing the priority bookmark does. Thanks
Debra

Sent from Yahoo Mail on Android 
 
  On Sat, Jul 24, 2021 at 5:53 AM, Andrew ***@***.***> wrote:   

I think the wavy line could have been good if it wasn't breaking for spaces
and lower parts of the letters. But I agree its not beautiful as it is.

I just had a look at the code and have made a pull request that does
'proper' two color underlines:
https://github.com/AndBible/and-bible/pull/1397

I haven't tested it well but so far so good.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by Dleemuse** [comment] 2021-07-25 02:43
Nice, can't wait to see this! 
D. 

Sent from Yahoo Mail on Android 
 
  On Sat, Jul 24, 2021 at 9:42 PM, Dlee ***@***.***> wrote:   Agreed, wavy Line does not look good. 
Debra

Sent from Yahoo Mail on Android 
 
  On Sat, Jul 24, 2021 at 9:41 PM, Dlee ***@***.***> wrote:   Yes, I just figured out recently what changing the priority bookmark does. Thanks
Debra

Sent from Yahoo Mail on Android 
 
  On Sat, Jul 24, 2021 at 5:53 AM, Andrew ***@***.***> wrote:   

I think the wavy line could have been good if it wasn't breaking for spaces
and lower parts of the letters. But I agree its not beautiful as it is.

I just had a look at the code and have made a pull request that does
'proper' two color underlines:
https://github.com/AndBible/and-bible/pull/1397

I haven't tested it well but so far so good.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by timbze** [comment] 2021-09-03 16:14
Fixed by #1556

**Closed as completed by timbze** 2021-09-03 16:14 UTC
Labels: Type: Support, Type: Discussion
