### ISSUE TITLE
Window divider weird speed changes

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3232] opened 2024-03-21 08:49 UTC
Hello,

When I adjust the divider line between the top and bottom screen it is sometimes extremely sensitive and overly fast (1 cm of finger movement brings it from top to bottom), and other times extremely slow (a finger scroll from top to bottom moves it about 1 cm).

https://support.andbible.org/scp/tickets.php?id=2530

**Comment by timbze** [comment] 2024-03-24 14:08
Duplicate of #3193

**Closed as completed by timbze** 2024-03-24 14:08 UTC
Labels: Type: Bug, Affects: Alpha
