### ISSUE TITLE
Intercept Bible URI-s and URL-s

### ISSUE THREAD

**Issue by ildar** [AndBible/and-bible#134] opened 2018-05-23 07:28 UTC
As you (Martin) wrote yourself:
вт, 2 мая 2017 г. в 2:01, Martin:
> There are some standard Sword uris. You will find reference to these in UriAnalyzer and use in LinkControl. They are specified in https://www.crosswire.org/wiki/Frontends:URI_Standard

Actual reference is now at: http://wiki.crosswire.org/Frontends:URI_Standard

It's a common practice for Android apps to react on related URIs and URLs. This generally help a lot with integration to other apps and opens a lot of customization opportunities.
The support code shouldn't be complicated. Please consider adding. Thanks.

**Comment by ildar** [comment] 2018-05-23 07:38
FYI this issue once was at old tracker: http://code.google.com/p/and-bible/issues/detail?id=188

**Comment by ildar** [comment] 2018-05-23 07:45
related: https://github.com/YakushevVladimir/BibleQuote-for-Android/issues/22 (in Russian)

**Comment by tuomas2** [comment] 2020-04-14 14:12
Related or duplicate #64

**Comment by timbze** [comment] 2021-04-15 23:27
Closing as duplicate of #64

**Closed by timbze** 2021-04-15 23:27 UTC
Labels: Good for starting contributors, Status: Preliminary, Type: Feature, Work amount: Moderate
