### ISSUE TITLE
More Filter Range Search Options

### ISSUE THREAD

**Issue by Lectric1** [AndBible/and-bible#2575] opened 2023-04-15 18:56 UTC
_**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

I like the ability to search old and new testament but have desired for a long time to have the ability to search just the Pentateuch or the Histories, or any other major sections of scripture. 

_**Describe the solution you'd like**
A clear and concise description of what you want to happen._

Simply in the "Find" feature have an option for Bibles to be searched based a feature where you can select a beginning book and ending book for the search, and/or list specific books. this could be hidden behind an 'advanced search' feature.

_**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered._

Simply add a couple more options to the "find" feature for things like The Gospels, The Histories, The Epistles, The Pentateuch, etc.

_**Additional context**
Add any other context or screenshots about the feature request here._

It would also go really well with a feature like this [one](https://github.com/AndBible/and-bible/issues/2556)

**Comment by timbze** [comment] 2023-04-16 10:58
Closing as duplicate of #2168 and #186

**Closed as completed by timbze** 2023-04-16 10:58 UTC
Labels: Type: Feature

**Comment by timbze** [comment] 2023-04-16 11:02
@Lectric1 thank you for your request. It would be a great feature to have, but since everything here is voluntary work we cannot guarantee when this feature will be worked on. If you are a software developer, or know someone who is who might have time to work on the feature, the help would be welcomed.
