### ISSUE TITLE
Date-based reading plan causes date (month) errors with other app languages

### ISSUE THREAD

**Issue by Schdefoon** [AndBible/and-bible#936] opened 2021-02-26 23:45 UTC
Hi,

I'm not sure if it is only on my device...
I build a custom reading plan following the instructions [here](https://github.com/AndBible/and-bible/wiki/Reading-Plans#custom-reading-plans) and verified my problem with the example I found [here](https://github.com/AndBible/and-bible/issues/292#issuecomment-557581268).
Both reading plans caused errors.
I simplified the reading plan to one single line:

`1=Feb-28;Lev 3-4,Ps.104,1Cor 12-13`
This is working

`1=Mar-1;Lev 3-4,Ps.104,1Cor 12-13`
This is not working

I'm getting an error. In the long message there is a line:
`java.text.ParseException: Unparseable date: "Mar-1/2021"`

I can use almost 60 lines from January to February without problems.
When using 365 lines for the whole year then the unparseable date is on Oct 16th.

I'm using v3.3.399 with Android 7.1.2 on a SM-G930F.

Is this a common error?

Thanks and best regards.

**Comment by Schdefoon** [comment] 2021-02-27 19:32
Ok -might depend on the language settings.
I did some new tests:

These single lines are working
- 1=Jan-28;Ps.1
- 1=Feb-28;Ps.1
- 1=Apr-28;Ps.1
- 1=Mai-28;Ps.1 (german Mai instead of english May)
- 1=Aug-28;Ps.1
- 1=Sep-28;Ps.1
- 1=Okt-28;Ps.1 (german Okt instead of english Oct)
- 1=Nov-28;Ps.1
- 1=Dez-28;Ps.1 (german Dez instead of english Dec)

Not working are Jun, Jul. The first three letters are the same in german as in english. And I have no idea what to use for Mar. In german it would be Mär or Mae or something like Mrz.

Or is it possible to set the language like you can set the versification (Versification=Vulg)?

**Comment by Schdefoon** [comment] 2021-02-27 19:54
Ok, it's "Juni", "Juli" and "M\u00e4rz" for reading plans on my german Android devices.

So the problem is solved for me. It might be difficult for users with other languages.

**Comment by timbze** [comment] 2021-03-04 15:18
> Ok, it's "Juni", "Juli" and "M\u00e4rz" for reading plans on my german Android devices.
> 
> So the problem is solved for me. It might be difficult for users with other languages.

Thank you for reporting it and figuring out what the issue is!

I will try to look at fixing it for the next release.

**Comment by timbze** [comment] 2021-04-05 14:34
Fixed in #951, don't know why this issue did not close

**Closed as completed by timbze** 2021-04-05 14:34 UTC
Labels: Type: Bug, Prio: Major, Reading plan
