### ISSUE TITLE
AB in Split window mode is buggy with multiple windows within AB... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#614] opened 2020-04-14 02:08 UTC
Using build 361 beta:

1. Create two windows in AB. With horizontal split. 
2. Now create split apps in Android putting AndBible at the bottom.
The two windows in AB end up in vertical mode.
3. Use reverse split option to make the windows horizontal split.
4. Try to move the split line for windows in AndBible and it jumps and the first window in AB disappears.

To bring back the two windows uncheck the reverse split box.

**Comment by tuomas2** [comment] 2020-04-14 07:27
Tried to reproduce but couldn't.

**Comment by bvahedy** [comment] 2020-04-14 07:39
Let me try a fresh install and see if it still happens.

**Comment by bvahedy** [comment] 2020-04-14 20:42
I tried it with a fresh install still the same thing happens. When in full screen I have two horizontal windows and then going to the split window this is what I end up with (see image).
![Screenshot_20200414-133332_And Bible](https://user-images.githubusercontent.com/46405809/79272032-b14aa300-7e55-11ea-9266-2a09d8e23bb3.jpg)

 There is definitely something wrong. We can wait and see if anyone else has the same issue.

**Comment by tuomas2** [comment] 2020-05-14 15:03
Again tried to reproduce wiht my mobile phone and with the modules you are using (including CSS) but could not reproduce. Can you try again? Can someone else reproduce?

**Comment by bvahedy** [comment] 2020-05-14 18:32
Just tried it again it's still doing it. The strange thing is that if I try to expand the size of the AB window so that it has 3/4 of the phone screen then it automatically switches the two AB windows to horizontal view. It's weird.

**Comment by tuomas2** [comment] 2020-05-15 07:40
I also noticed some weird behavior, but in vertical split mode. Will report later more detailed description.

**Comment by tuomas2** [comment] 2020-05-21 13:15
Will be fixed in build 369

**Closed** 2020-05-21 13:15 UTC
Labels: Prio: Major, Type: Bug
