### ISSUE TITLE
Word and phrase search in books documents and dictionaries

### ISSUE THREAD

**Issue by KyleBroflowski** [AndBible/and-bible#2250] opened 2022-09-21 16:21 UTC
The search/find button is greyed out for documents like commentaries and  books
I request search feature for words and phrases from commentary and document books like Early fathers series or commentaries of St John Chrysostom. 
Enable search feature for every document.

**Comment by tuomas2** [comment] 2022-09-22 09:07
Duplicate of #2247

**Closed as completed by tuomas2** 2022-09-22 09:07 UTC
Labels: Type: Feature
