### ISSUE TITLE
App crashes when sharing a speak bookmark

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1051] opened 2021-05-14 04:21 UTC
Set a speak bookmark
Click speak bookmark
Click 3 dot menu
Click share

Expected: share menu opens

Actual: app crashes

Might be related to: https://github.com/AndBible/and-bible/issues/1039
Reported here: https://support.andbible.org/scp/tickets.php?id=488

**Comment by tuomas2** [comment] 2021-06-17 15:17
Duplicate of #1072

**Closed as completed by tuomas2** 2021-06-17 15:17 UTC
Labels: Type: Bug, Affects: Beta, Prio: Major
