### ISSUE TITLE
Top verse covered when switching from full screen

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#281] opened 2019-02-06 23:48 UTC
When in full screen mode on chapter 2 of any Bible book , swiping to the right will bring you to chapter 1 verse 1 at the top of the screen. Then if you double tap the menu bar covers the first verse and you can't scroll  down to see verse one.

Expected behavior:
When verse 1 of chapter 1 is at the top of the screen in full screen mode, coming out of full screen mode should bring verse one below the menu bar at top of the screen.

**Comment by ericjding** [comment] 2019-02-08 05:45
This is a challenging design issue. Actually, I'd argue that the program is behaving as expected -- full-screen mode _shouldn't_ affect the placement of the text on the screen. Otherwise, what would happen is that the text would be moved down by the height of the status bar + toolbar in this special case (visually jarring), but not in any other scenario. So what happens if the user then double-taps again; should AB now move verse 1:1 back up toward the top?

I see the dilemma you're raising, but I think the solution you propose also results in a different issue arising. I'm not saying it's not an issue, but I think any proposed solution needs to be carefully weighed against its downsides.

**Comment by tuomas2** [comment] 2019-02-08 06:53
One real issue here is at least that 'you can't scroll down to see the verse one'.

**Comment by bvahedy** [comment] 2019-02-08 07:37
Eric, if verse one is under the menu bar and we don't want to bring verse
one down below the menu bar, then we should at least allow the user to side
down to see verse one.

 In the case where the user double taps to go to full screen mode, just to
make it easy, we could just hide the menu bar and leave it's place blank
instead of moving everything up.

Ben

**Comment by ericjding** [comment] 2019-02-09 10:59
@bvahedy, thanks for clarifying the critical issue. I stand corrected. I agree with you both that this is a real issue; and what's more, I realize that it's a regression, since the previous version of full-screen mode actually did slide the text up and down with the toolbar. Of course, now that we have a paradigm where full-screen mode can be triggered automatically with forward scrolling means more complications.

So is there an argument for the text display behaving fundamentally differently in the case of double-tap (e.g., move the text upward with the toolbar as in older versions of AB) than in the case of auto-hide with scrolling?

**Comment by tuomas2** [comment] 2019-02-09 11:11
Text should not move when switching between fullscreen and back. But we can add extra space before text so that text can be scrolled down to view verse one.

**Comment by ericjding** [comment] 2019-02-10 06:07
@tuomas2 on my phone, I compared the old AB with the current situation. If I were to choose between the old paradigm when double-tapping (text jumps upward or downward) or the paradigm you suggest (add extra space, as for example the screen appears if I first go to verse 1:1 and then full-screen mode), I'd be torn between the distraction of text jumping up and down in this particular edge case and the ugliness of white space at the top of the screen above verse 1:1. I think I'd personally lean toward not just having extra white space.

I don't have strong feelings about it -- after all, we're talking about an edge case that only occurs 66 times out of over thirty thousand verses. :-) Still, I wonder aloud if this particular scenario calls for an exceptional approach (e.g., moving the text up or down with the toolbar as AB used to do) compared to all the others.

**Comment by bvahedy** [comment] 2019-02-10 08:21
I agree the proper method would be to move verse 1 down by the hight size
of The menu bar when jumping out of the full screen mode. The
implementation of smooth scroll will make it almost un-noticable to the
eye. But I can live with it either way.

**Comment by bvahedy** [comment] 2019-02-14 22:42
I'm reopening this, line 1 is still covered and can't be seen.

**Comment by tuomas2** [comment] 2019-02-28 07:22
> I'm reopening this, line 1 is still covered and can't be seen.

But now there's extra space so you can scroll so the first verse is visible. This was the fix I was intending to do. I would rather not move the text when switching from/to fullscreen. I would think that it is more likely that user is already reading the visible area (not the first line), so that it would be disturbing if that line would suddenly move. Closing this now, but feel free to continue discussion on the closed ticket if there's still some necessary arguments.

**Comment by bvahedy** [comment] 2019-02-28 17:04
Yes, there is an extra space but we need one more line space to reveal the first line. When scrolling down verse one is still partially covered.

**Comment by tuomas2** [comment] 2019-02-28 18:21
![screenshot_20190228-201759](https://user-images.githubusercontent.com/5811789/53588685-34e3fa80-3b96-11e9-9144-7ac706cf97e0.png)

Where is your chapter numbers? This is how it looks like for me.

**Comment by tuomas2** [comment] 2019-02-28 18:23
maybe height of system statusbar is indeed missing.

**Comment by bvahedy** [comment] 2019-03-01 01:36
In the video you can see when the menu appears it tells you what
chapter/verse you are in. But the first line of verse one hides the verse
number and you can not scroll down to see that line, that is what the bug
is. There just needs to be an additional white line added so it can be
scrolled down far enough.

**Comment by tuomas2** [comment] 2019-03-01 07:53
Will be fixed in 304

**Closed** 2019-03-01 07:53 UTC
Labels: Affects: 3.0, Prio: Minor, Type: Bug
