### ISSUE TITLE
Downloading any n documents causes verses to be highlighted n times for session

### ISSUE THREAD

**Issue by RuggMatt** [AndBible/and-bible#1965] opened 2021-12-02 15:13 UTC
**Describe the bug**

Verse is highlighted twice

Steps to reproduce.
1. Open AndBible to any highlighted verse
2. Navigate to Download Documents and download any 2 documents
3. Navigate back to main Bible view

Expected
Verse remains only highlighted once

Actual
Verse appears to be highlighted multiple times.

Restarting the app shows the verse only highlighted once again.

Device info:
And Bible version: 4.0.621#6d631e9eb standard release (built 25/11/21 16:34:57)
Android version: 12
Android SDK version: 31
Manufacturer: Google
Model: Pixel 4 XL
Storage Mb free: 26701
WebView version: 96.0.4664.45
SQLITE version: 3.32.2
Used heap memory in Mb: 81
Max heap memory in Mb: 256

![Screenshot_20211202-080225.png](https://user-images.githubusercontent.com/8870594/144449066-23f1bde8-16af-48bb-9b4c-9a7436922906.png)

**Comment by RuggMatt** [comment] 2021-12-02 15:15
Logcat https://support.andbible.org/scp/tickets.php?id=1090

**Comment by timbze** [comment] 2021-12-02 16:10
Probably duplicate of #1623, but didn't have nice repro steps before.

**Comment by tuomas2** [comment] 2021-12-02 16:15
Yes I believe so

**Comment by tuomas2** [comment] 2023-08-31 12:21
Seem to be fixed already

**Closed as completed by tuomas2** 2023-08-31 12:21 UTC
Labels: Type: Bug, Prio: High
