### ISSUE TITLE
Option to use Human audio narrations (supplied by user) 

### ISSUE THREAD

**Issue by christubuntu** [AndBible/and-bible#2631] opened 2023-06-15 09:25 UTC
In addition to the tts, can we have option for the app to recognize audio files from the many free to use Bible narrations?
Ex. I have this Bible app (https://play.google.com/store/apps/details?id=com.bestweatherfor.bibleoffline_pt_ra) that has option to download audio narrations offered within the app. But if you go to it's Appdata (/storage/emulated/0/Android/data/com.bestweatherfor.bibleoffline_pt_ra/files/com.bestweatherfor.bibleoffline_pt_ra) you can rename your own files to match the ones it downloaded, Delete the original audio and the app will play your own.
If dev finds this feature useful like I do, he could just setup any naming scheme for all Bible books and it'll be up to the user to rename the files accordingly

**Comment by tuomas2** [comment] 2023-06-15 10:35
Duplicate of #1909

**Closed as completed by tuomas2** 2023-06-15 10:35 UTC
Labels: Type: Feature
