### ISSUE TITLE
font size for different language text

### ISSUE THREAD

**Issue by howdev** [AndBible/and-bible#2233] opened 2022-09-06 04:05 UTC
**Is your feature request related to a problem? Please describe.**
using the same font size for all language text is not suitable. A font size for a language is different size in another language. The English text for example is conformable at size 16 but not in Asian text. The Chinese text is more dense and it needs separate font size.

**Describe the solution you'd like**
Allow to save different font size for different language text.

**Comment by agrogers** [comment] 2022-09-06 06:29
My solution to that problem is to add extra windows for specific documents or languages or setup a new workspace altogether. It's not ideal. But it works pretty well.

**Comment by howdev** [comment] 2022-09-06 08:15
workspace is a workaround, not convenient as it doesn't have a shortcut to switch workspaces.

**Comment by agrogers** [comment] 2022-09-06 11:46
You can switch workspaces by swiping left or right on the verse at the top.
Or swipe down on the verse to access the workspace list.

This video might help
https://youtu.be/3YB3_QH8zew

**Comment by timbze** [comment] 2022-09-06 12:01
Closing as duplicate of #2204

**Comment by timbze** [comment] 2022-09-06 12:01
@howdev you can also check the comments on #2204

**Closed as not planned by timbze** 2022-09-06 12:01 UTC
Labels: Type: Feature
