### ISSUE TITLE
Show a 'verse of the day' in the notifications or when opening the app

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#2356] opened 2022-11-11 02:07 UTC
Other apps have the option to show a verse of the day in a notification or when the app is opened.

- A random verse may not be that useful. 
- But throwing up one of the bookmarked verses could be quite good. Reminding people of a verse they thought was important has advantages
- Could limit the 'verse of the day' to specific labels. 
- If this was shown in the app, it could also include a commentary for that reference. It would act a little like a devotional but just pulled automatically from Barnes or Matthew Henry (probably too long) or some commentary(s) the user nominates.
- Could also make it like a memory verse test. Show the reference with a button to reveal the the verse itself.

This request has come through our email support.

**Comment by tuomas2** [comment] 2022-11-12 09:00
I think this is duplicate of #184?

**Closed as completed** 2022-11-12 09:01 UTC
Labels: Type: Feature
