### ISSUE TITLE
get current ab published in huawei and samsung stores

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1449] opened 2021-07-30 05:58 UTC

**Comment by timbze** [comment] 2021-07-30 11:48
Duplicate of #909?

**Comment by tuomas2** [comment] 2021-07-30 11:58
Kind of, but actually I already initiated #909 some moths ago (forgot that ticket and it's not on board). Both publishing processes just were stuck for some reason. Now that I have mainly boring bugfixing left, I might feel like finishing this :-)

**Comment by tuomas2** [comment] 2021-08-02 11:11
Re-submitting to Samsung.

> Publish was rejected for 2 reasons:
> 
> - Publishing in iran is not allowed due to Iran policy
> RESOLUTION: do not publish there. (adjusted country/region preferences)
> 
> - Application uses copyrighted materials without permission owned by a third party.
>  https://play.google.com/store/apps/details?id=net.bible.android.activity
> 
> RESOLUTION: I am actually the copyright holder and manage also the Play Store entry.  You can see that the app is published by And Bible Open Source Project, and I am the lead developer of the And Bible Open Source Project. See https://github.com/AndBible/and-bible.  See also https://github.com/AndBible/and-bible/issues/1449 (I'm writing there about the progress to get app published here).

**Comment by tuomas2** [comment] 2021-08-02 11:27
Huawei submission was rejected last time due to this message:


> [Description]: An error occurs in your App. Please see the attachment, here is the path: Go to Console > App Service > AppGallery Connect>Find your app from the list and click the version to check the attachment. Please refer to the rule 3.1 of "AppGallery Review Guidelines": https://developer.huawei.com/consumer/en/doc/distribution/app/30202 [Test Step]: When clicking "Download" any e-books, your App prompts error [Test Environment]: Wi-Fi connection, Android 10.0/EMUI 10.0 (Mate 30), Android 10/EMUI 10.0(P30),Multilingual settings. [Suggestion]: Please identify it accordingly. Then revise and resubmit your App for review.

Re-submitting with these instructions:
> If you are reviewing this from China, you might not be able to download documents from the document repositories due to Chinese restrictions. Outside of china app should work perfectly. I can also provide you a test zip file that you can install without needing to download documents.

**Comment by tuomas2** [comment] 2021-08-02 11:27
(to both app stores, I was submitting current stable, i.e. version 3.3.400)

**Comment by tuomas2** [comment] 2021-08-04 15:41
From Huawei good news:

> Dear developer,
> 
> Your application submitted at 19:27:21,August 02,2021 for releasing Bible Study app, by And Bible Open Source Project 3.3.400 was approved. Bible Study app, by And Bible Open Source Project 3.3.400 is now available for download on HUAWEI AppGallery.
> Review comment: Your App has been approved.
> [Test Environment]: Wi-Fi networking. EMUI 10.0.0(P30 Pro), /EMUI 11.0.0(P40 Pro). Multilingual environment.
> Notes: Your App contains Christian content, which does not conform to requirements such as religious etiquette and cultural customs in some regions. The display of your app in your selected release regions/countries has been affected. To check the final release countries/regions of your app, go to Version information > Country/Region for release after your app is approved.
>

**Comment by tuomas2** [comment] 2021-08-04 15:51
also Samsung has approved:

> Application Title
> Bible Study app, by And Bible Open Source Project
> Result
> Ready for Sale
> Details
> 
> : Congratulations on passing the app review. Your app will be for sale based on the publication option you've selected at submission.
> 
> - Publish automatically: Your app will be for sale within 10 minutes. If your app fails the second phase of the app review process, you will be notified about the issues that caused the failure and your app will be suspended in Galaxy Store.
> 
> - Publish on date: Your app will be for sale on the specified date.
> 
> - Publish manually: You need to publish the app manually or set up the publication date.

**Closed as completed** 2021-08-04 15:54 UTC
Labels: Type: Task

**Comment by agrogers** [comment] 2021-08-04 20:55
Great!
