### ISSUE TITLE
Optionally get the user to provide a Google or MS account so we can easily backup the db etc

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1166] opened 2021-06-19 12:38 UTC
I would personally like this. Then I could just set an option to backup regularly and And Bible will do it automatically. It would also be  the first step to be able to keep multiple devices in sync.

**Comment by tuomas2** [comment] 2021-06-19 12:56
I think there's somewhere an issue already for this

**Comment by tuomas2** [comment] 2021-06-19 12:56
#974

**Comment by agrogers** [comment] 2021-06-19 13:03
Oh, it is. I should have checked. #974  is closed. We don't like this idea?

**Comment by timbze** [comment] 2021-06-19 14:08
> Oh, it is. I should have checked. #974  is closed. We don't like this idea?

Just look why it's closed 😊 it's duplicate of #370

**Comment by tuomas2** [comment] 2021-06-19 14:36
Duplicate of #370

**Closed as completed by tuomas2** 2021-06-19 14:36 UTC
Labels: Type: Feature, Prio: Minor, Status: Preliminary
