### ISSUE TITLE
Toolbar customization to hide speak ear icon.... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#237] opened 2019-01-23 22:10 UTC
Request made by user to:
add an option in the settings to hide "ear icon" speak button.

**Comment by tuomas2** [comment] 2019-01-24 08:42
Will be implemented in #195

**Comment by tuomas2** [comment] 2019-01-24 08:43
Duplicate of #195, closing

**Closed by tuomas2** 2019-01-24 08:43 UTC
Labels: Feature, Prio: Low
