### ISSUE TITLE
Screen Freezing 

### ISSUE THREAD

**Issue by Dleemuse** [AndBible/and-bible#1114] opened 2021-05-29 23:51 UTC
When trying to highlight verse(s), screen freezes (and AB crashed once), no highlight appears. Hitting back button & coming back to desired verse fixed the problem several times, except when AB crashed.

Thanks,

Debra

**Comment by tuomas2** [comment] 2021-05-30 06:23
When freezing happens, it would be helpful if you used main menu -> repprt a bug feature, so we can get logcat to be inspected.

**Comment by tuomas2** [comment] 2021-05-30 06:32
Probably duplicate of #1099

**Comment by Dleemuse** [comment] 2021-05-31 19:58
This is possibly related to #1099.

Debra

**Comment by tuomas2** [comment] 2021-06-03 15:02
Closing as duplicate of #1099

**Closed as completed by tuomas2** 2021-06-03 15:02 UTC
Labels: Type: Bug, Prio: Major
