### ISSUE TITLE
Bible text in capital letters - so kids can learn reading

### ISSUE THREAD

**Issue by msavli** [AndBible/and-bible#1176] opened 2021-06-24 17:16 UTC
Can you add feature Bible text in capital letters - so kids can learn reading?

**Comment by timbze** [comment] 2021-06-24 21:45
It is possible to take a specific document (module) in AndBible version 3.4 (now in beta), and add css styles to make it uppercase. See https://github.com/AndBible/and-bible/wiki/Custom-CSS-for-modules-for-And-Bible. I tested it with KJV and it worked.

For KJV I simply added a .css file with:
```css
.sword-KJV {
	text-transform: uppercase;
}
```

@tuomas2 will have to decide if we'll add this as a feature in the app.

**Comment by agrogers** [comment] 2021-06-24 23:03
The custom css is a cool feature. Probably beyond most users capability
though. I wonder if another document type which allowed the sharing and
installing of Style files could ever be justified.

**Comment by tuomas2** [comment] 2021-06-25 05:48
I don't think I would include this in And Bible, as I doubt there is very small amount of usage for this. But CSS customization is somethign that would enable this for a single user that really wants to do something different.

**Comment by tuomas2** [comment] 2021-06-25 08:38
We could even have "big letters KJV" included in our repository, with this CSS.

**Comment by tuomas2** [comment] 2021-06-25 08:38
(or other public domain bible -- but not NASB or other copyrighted one)

**Comment by agrogers** [comment] 2021-06-25 22:33
It would be helpful for me to have somewhere in And Bible the location of the CSS files need to go. I have really struggled in the past just trying to find where stuff is installed on my devices

**Comment by timbze** [comment] 2021-07-01 16:23
> It would be helpful for me to have somewhere in And Bible the location of the CSS files need to go. I have really struggled in the past just trying to find where stuff is installed on my devices

Follow these directions, and I think you will get the idea
1. Export KJV module from AB
2. Unzip to your computer, you will now find `mods.d` and `modules` folder
3. In `mods.d` folder, edit the kjv.conf file and add this line at the bottom: `AndBibleCSS=style/style.css`
4. In the same kjv.conf file, look at what the "DataPath" value is close to the top. Navigate to that directory in the `modules` folder. In this case it's `modules/texts/ztext/kjv/`
5. In `modules/texts/ztext/kjv/`, add a folder named `style`, and add `style.css` file to `style` folder (see point 3)
6. Add the css I have above to the style.css file
7. Now zip the `mods.d` and `modules` folder together again, and import to AB as document. This will now replace the original KJV module and make it all caps.
8. To revert, you will need to remove the module first, and then reinstall from "Downloads"

**Comment by timbze** [comment] 2021-07-01 16:24
@msavli which Bible version would you like all caps? As Tuomas says, if you're ok with a module that is in the public domain then we could make a duplicate of a current module and add the style so that you have a separate ALL CAPS document.

**Comment by tuomas2** [comment] 2021-07-01 17:16
As a future feature request, we could actually have "add on" css modules that implement something custom to all installed modules.

**Comment by agrogers** [comment] 2021-07-02 01:00
Thanks for that info Timmy.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by bvahedy** [comment] 2021-07-02 03:29
We can also use fonts that are all caps like this without implementing any css code:
![Screenshot_20210701-202507_Bible Study](https://user-images.githubusercontent.com/46405809/124216374-00a4df80-daab-11eb-9286-dfde6036c13a.jpg)

**Comment by tuomas2** [comment] 2021-07-02 06:00
Good idea @bvahedy ! Just use "Sans Serif Smallcaps" font (built in in android) and that's it!

**Comment by tuomas2** [comment] 2021-07-02 06:07
I guess we can close this issue then.

**Closed as completed by tuomas2** 2021-07-02 06:07 UTC
Labels: Type: Feature, Prio: Minor, Status: Preliminary
