### ISSUE TITLE
Swipe  to next chapter bug... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1057] opened 2021-05-15 04:30 UTC
In build 522.2 beta:

I was reading Mark chapter four. On verse one, I swiped left to go to chapter five and then swipe down  to see the last verse in chapter four.

What happens:
The end of chapter three appears.

Expected result:
End of chapter four schools display.

![Screenshot_20210514-212356_Bible Study](https://user-images.githubusercontent.com/46405809/118347924-8b317f80-b4fb-11eb-85e3-a30a0feac21b.jpg)

**Comment by bvahedy** [comment] 2021-05-15 04:45
I closed the app and reopened it and now I can't duplicate this. Good thing I took a screenshot otherwise I would have thought I'm going crazy.

**Comment by tuomas2** [comment] 2021-05-15 14:46
I wonder if chapter 4 appeared after chapter 5

**Comment by bvahedy** [comment] 2021-05-15 20:03
No I checked and the whole of chapter 4 was missing as is it never existed.

**Comment by tuomas2** [comment] 2021-05-15 20:20
it looks similar as old bug that I reported years ago (there's ticket somewhere, not sure if it's closed or not). Though unbelievable that it's still alive...

**Comment by bvahedy** [comment] 2021-05-15 23:36
Well something must have triggered it for it to appear again. I'm also
getting another bug that I cannot duplicate, it has occurred twice now but
I don't know what steps causes it. the study pad doesn't show when you tap
on the bookmark lables. But closing the app and reopening it fixes this
issue.

**Comment by tuomas2** [comment] 2021-08-05 08:41
Duplicate of #136

**Closed as completed by tuomas2** 2021-08-05 08:41 UTC
Labels: Type: Bug, Prio: Major
