### ISSUE TITLE
Speak bar missing when setting up sleep timer... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1091] opened 2021-05-24 15:17 UTC
When setting repeat passage or sleep timer and tapping the play button. The speak toolbar is missing at the bottom of the screen.

![Screenshot_20210524-005519_Bible Study](https://user-images.githubusercontent.com/46405809/119368925-71650a80-bc68-11eb-9010-95ecd3fff297.jpg)

**Comment by timbze** [comment] 2021-05-24 15:48
Duplicate of #1050 :)

**Closed as completed by timbze** 2021-05-24 15:48 UTC
Labels: Type: Bug, Prio: Major
