### ISSUE TITLE
[Obsolete / Discussion] header menu has completely disappeared

### ISSUE THREAD

**Issue by joshuad31** [AndBible/and-bible#1744] opened 2021-09-22 15:18 UTC
# Bug topic moved to #1756 , this continues as a free-form discussion ticket 

**Describe the bug**
header menu has completely disappeared

**Bug was found on And Bible version**
The newest build I just upgraded to this morning... I can't get into settings so I cant tell you what build this is but its the latest

**To Reproduce**
1. Open up and bible and immediately menus are gone

**Expected behavior**
Top menu bar should be visible

**Screenshots**
![Screenshot_20210922-101317_Bible Study](https://user-images.githubusercontent.com/5976059/134371449-03ea05aa-bf65-45a5-8afe-45992c8bca3b.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Note 8
 - OS: Android
 - Version 8.0.0

**Additional context**
I WILL PAY ANY AMOUNT OF MONEY TO GET ACCESS TO MY BOOKMARKS! I need my data back!  This is a nightmare.  Please please someone help me.

**Comment by joshuad31** [comment] 2021-09-22 15:19
Please God I need my bible back...

**Comment by tuomas2** [comment] 2021-09-22 15:23
Thank you for reporting this issue!

If you click where the menu is supposed to be, does something happen? Is it like like invisible toolbar?
Does it happen after restarting app? What about does it  happen after restarting phone?

**Comment by joshuad31** [comment] 2021-09-22 15:24
@tuomas2 yes something does happen BUT I can't see what I'm clicking on till I click it.  I'm completely blind in this update... please please I need to rollback.  I have to read my bible today.

**Comment by joshuad31** [comment] 2021-09-22 15:25
@tuomas2 I'll pay any amount of money to get the old version back on my phone, please!

**Comment by bvahedy** [comment] 2021-09-22 15:25
You may also be in full screen mode, try double tapping on the screen to exit full screen mode, if that's the case.

**Comment by tuomas2** [comment] 2021-09-22 15:27
This does not look like full screen mode. This is weird rare issue that is not easy to reproduce. Can you try to switch to night mode? Do you get 3-dot option menu open by clicking right-top corner?

**Comment by joshuad31** [comment] 2021-09-22 15:28
@bvahedy I am not in full-screen mod. I have double-clicked it.
@tuomas2 I restarted my phone. It did not help.

**Comment by tuomas2** [comment] 2021-09-22 15:28
Phone toolbar should look something like this
![Screenshot_20210922_182815](https://user-images.githubusercontent.com/5811789/134373769-a5fb785c-c6dc-4ee8-b683-8fb71da68ea0.png)

**Comment by tuomas2** [comment] 2021-09-22 15:29
and there you should find night mode switch

![Screenshot_20210922_182903](https://user-images.githubusercontent.com/5811789/134373880-c9c4d482-bdd2-4602-aea1-78fcc2cf5486.png)

**Comment by joshuad31** [comment] 2021-09-22 15:29
![Screenshot_20210922-102838_Bible Study](https://user-images.githubusercontent.com/5976059/134373871-1acdfd63-563b-49cc-b18c-a328e1af044b.jpg)
@tuomas2 see night mode

**Comment by tuomas2** [comment] 2021-09-22 15:30
Do you see menus in general? Like main menu

![Screenshot_20210922_182945](https://user-images.githubusercontent.com/5811789/134374045-e5c2b78f-9046-4d92-83ca-07cf6136cf78.png)

**Comment by joshuad31** [comment] 2021-09-22 15:30
![Screenshot_20210922-102959_Bible Study](https://user-images.githubusercontent.com/5976059/134374055-bd7127b7-5cc8-4635-9ba8-a2a1ad5fc9ba.jpg)
@tuomas2 further proof the menus are invisible

**Comment by tuomas2** [comment] 2021-09-22 15:31
toolbar is invisible, but you can see popup menus and main menu? Main menu can be opened also with slide gesture from left side of the screen.

**Comment by joshuad31** [comment] 2021-09-22 15:31
@tuomas2 there are no menus in this app... ever. All gone

**Comment by tuomas2** [comment] 2021-09-22 15:32
apparently 3dot menu (from right-top corner) works, but main menu does not open at all?

**Comment by joshuad31** [comment] 2021-09-22 15:33
@tuomas2 my bookmarks are all GONE! ... WHY? Where did they go?

**Comment by tuomas2** [comment] 2021-09-22 15:34
Please calm down. I'm here trying to help. I don't need money. I need some patience and some information. I have tomorrow whole day to try to figure this out, if I get the information I need.

**Comment by joshuad31** [comment] 2021-09-22 15:34
@tuomas2 main menu does open from the right AND the top menu will appear after I have two bible reading sessions open simultaneously.

**Comment by joshuad31** [comment] 2021-09-22 15:35
![Screenshot_20210922-103451_Bible Study](https://user-images.githubusercontent.com/5976059/134374961-fd3a73be-15da-43a7-8ac3-419db9401296.jpg)

**Comment by tuomas2** [comment] 2021-09-22 15:36
Okay, great. Do you find your bookmarks too?

**Comment by joshuad31** [comment] 2021-09-22 15:37
I eventually did find my bookmarks but when I return back from the left menu screen it does this... but then I click on it again and it goes back to something that makes more sense.  This whole experience is very confusing.

How can I export my bookmarks to some other app?

![Screenshot_20210922-103611_Bible Study](https://user-images.githubusercontent.com/5976059/134375284-82116da4-2542-4b02-9a47-7e32694c532b.jpg)

**Comment by joshuad31** [comment] 2021-09-22 15:38
@tuomas2 I can't use this app anymore I just need to get my data out.  How do I export all my data?

**Comment by tuomas2** [comment] 2021-09-22 15:38
If you can access main menu -> backup & restore, you can backup your old db and switch to the earlier version.

**Comment by joshuad31** [comment] 2021-09-22 15:39
@tuomas2 are there instructions for the switch?

**Comment by tuomas2** [comment] 2021-09-22 15:41
Yes, https://github.com/AndBible/and-bible/wiki/FAQ#how-do-i-downgrade-from-40-to-33

**Comment by joshuad31** [comment] 2021-09-22 15:42
@tuomas2 ok perfect I'll figure this out sometime today. Thank you

**Comment by tuomas2** [comment] 2021-09-22 15:43
Are you tomorrow there to answer questions when I try to figure out a way to reproduce / fix this issue?

**Comment by tuomas2** [comment] 2021-09-22 15:44
You are the first one to report such an issue, but I'm afraid there might be some other too. I paused the new version rollout for now until we will get this issue fixed.

**Comment by tuomas2** [comment] 2021-09-22 15:47
Can you still, before you downgrade, send a bug report via main menu -> report a bug? I might get some important extra info about the issue via log file.

**Comment by joshuad31** [comment] 2021-09-22 15:48
@tuomas2 ok will try

**Comment by tuomas2** [comment] 2021-09-22 15:51
Tried quickly to reproduce with emulator (running Android 8.0) but it was all OK. Will need to remote debug this on Samsung Note 8 device via Samsung online dev tools...

**Comment by joshuad31** [comment] 2021-09-22 15:51
@tuomas2 Can't downgrade with instructs error is "app not installed
![Screenshot_20210922-104811_Package installer](https://user-images.githubusercontent.com/5976059/134377959-919a90a4-ddb8-4eec-ae8b-6ee0740040ba.jpg)
"

**Comment by tuomas2** [comment] 2021-09-22 16:07
did you uninstall first?

**Comment by uniqueid001** [comment] 2021-09-22 16:11
@joshuad31 You should also be able to access the main menu by swiping in from the left side even though you can't see the button in the toolbar.

**Comment by uniqueid001** [comment] 2021-09-22 16:16
@tuomas2 This looks like something I have/can see:  only on my old phone (Moto G5 Plus, Android 8.1) and only when I rotate it counterclockwise to landscape.  I see it with my locally-built debug flavor app.  The first/left window displays correctly, and the background for the second/right/last window appears over the top of the toolbar's region.  I figured it is some weird quirk that only affected that one situation and not something that would affect a larger audience.  I should also note that the storage on that device is nearly full, in case that affects something.  

The released version (and I think 3.3 also) is exhibiting an odd quirk on that same device where the first/left window and the toolbar are "blank" and covered by the background of the second/right/last open window.  Again, this is only when I rotate to the left/counterclockwise and not to the right nor in portrait.  It flickers a bit before stabilizing, as if something is repeatedly triggering a layout or paint before finally drawing the second window's background color everywhere.  Does this help you think of something to investigate?

I do not see either of these behaviors on my Moto G Power (2020), Android 11.

**Comment by uniqueid001** [comment] 2021-09-22 16:33
Some more observations, using my locally-built debug app:
 * I can activate the buttons and controls in the toolbar, even though they are not visible
 * While animating the slide-out of the navigation drawer, the toolbar and the first window are displayed correctly.  The notification bar flickers with the second window's background.
 * When the nav drawer is closed, then the second window's background paints over the first window
 * Sliding the window buttons causes the covered part of the first window to be repainted correctly
 * Opening the overflow menu, then closing it, causes it's portion of the toolbar to become repainted and remain visible

(PS. my windows have different background colors, which makes it easy for me to identify that one was painting over everything else)

**Comment by joshuad31** [comment] 2021-09-22 16:46
> did you uninstall first?

Ok finally everything is back to normal. Please don't make me upgrade again. Thank you.

**Comment by tuomas2** [comment] 2021-09-22 16:50
@uniqueid001 thats valuable info. any help figuring this out (you or anyone else) is highly valued.

@joshuad31 all upgrades are optional. check your google play auto upgrade settings

**Comment by joshuad31** [comment] 2021-09-22 16:52
@tuomas2 Okay, I fixed it thanks.
How can I give to this project? This has been my favorite bible for forever.

**Comment by bvahedy** [comment] 2021-09-22 17:00
@joshuad31:  you should make a backup of your bookmark database and your Bible modules. There is a lot of value in upgrading. There are new functionalities that will make your life easier. Just a thought!

**Comment by joshuad31** [comment] 2021-09-22 17:02
... my phone is messed up thou, all of the file path locations for downloads are impossible to get to. No changes to my phone.

**Comment by bvahedy** [comment] 2021-09-22 17:15
Use x-plore file manager, it will allow you to access the
Android/data/net.bible.android.activity directory.

**Comment by tuomas2** [comment] 2021-09-23 05:34
I'm 99% confident that 2f6e782 will fix this issue. @joshuad31, I guess you might not want to help in testing this, but if you are (you can consider it as a donation of your time and work for the Lord; and remember that with backups you can allways revert back to 3.3), please let me know. I can produce a test build for you.

**Comment by tuomas2** [comment] 2021-09-23 05:53
Here is a test build apk to test if my fix really fixes the toolbar issue reported here: https://github.com/AndBible/and-bible/releases/tag/build-605-toolbarfix

**Comment by joshuad31** [comment] 2021-09-23 05:54
@tuomas2 Because I have had some time to calm down I'm willing to try and help

**Comment by joshuad31** [comment] 2021-09-23 06:07
@tuomas2
![header dissapears](https://user-images.githubusercontent.com/5976059/134461192-804f16a9-a14a-4f3d-a61b-4164a6bd2e98.png)
Unfortunately no... still this image proves there is an issue. I can download software and permit you to remotely access my phone if you need to.

I think now that I have had time to acclimate to the changes I could get by with the invisible menus although the initial shock was quite jarring being that the most valuable app I have on my phone is this one.

**Comment by joshuad31** [comment] 2021-09-23 06:09
@tuomas2 I have to go to bed but when I wake up I can try again. or something. Now that I know how to back up my bookmarks and downgrade if need be I feel much better about this now.

**Comment by tuomas2** [comment] 2021-09-23 06:10
Okay, thank you. I will try to figure out something to fix it better. It looks like there's some "improvement" over earlier one already now, but it's not "quite there"... :-)

**Comment by tuomas2** [comment] 2021-09-23 06:11
Just to make sure, did you try installing apk from the link I provided (https://github.com/AndBible/and-bible/releases/tag/build-605-toolbarfix)?

**Comment by joshuad31** [comment] 2021-09-23 06:28
@tuomas2
![Bible Study](https://user-images.githubusercontent.com/5976059/134463066-65078601-c618-4928-9709-63d904e0af88.jpg)

**Comment by joshuad31** [comment] 2021-09-23 06:28
@tuomas2 it is identical to how it was previously as far as I can tell.

**Comment by tuomas2** [comment] 2021-09-23 06:31
> @tuomas2 it is identical to how it was previously as far as I can tell.

Good to know.

**Comment by tuomas2** [comment] 2021-09-23 06:31
> @tuomas2
> ![Bible Study](https://user-images.githubusercontent.com/5976059/134463066-65078601-c618-4928-9709-63d904e0af88.jpg)

That looks correct.

**Comment by tuomas2** [comment] 2021-09-23 08:27
Note 8 is not (any more) available in Samsung Remote Test Lab (https://developer.samsung.com/remotetestlab/rtlDeviceList.action) :-/ 

Nor any other device that has Android 8.

**Comment by tuomas2** [comment] 2021-09-23 08:57
Upgraded several dependencies in the hope that it might fix this weird issue ( a47429dc3ed6391a6009b70bf3635e5493ee529b). New test build coming soon.

**Comment by tuomas2** [comment] 2021-09-23 12:28
New test build: https://github.com/AndBible/and-bible/releases/tag/build-605-toolbarfix5

**Comment by tuomas2** [comment] 2021-09-23 13:30
Can you @joshuad31 test again with https://github.com/AndBible/and-bible/releases/tag/build-605-toolbarfix5 and let me know the result.

**Comment by uniqueid001** [comment] 2021-09-23 14:14
Rev 4e124deafbebc7f9a4fa1fe7118bfec2764cb0fa does not fix it on my G5.

**Comment by tuomas2** [comment] 2021-09-23 14:16
Thank you @uniqueid001. Sad thing is that I'm starting to run out of ideas here... Super weird issue.

**Comment by tuomas2** [comment] 2021-09-23 14:37
> @tuomas2 This looks like something I have/can see: only on my old phone (Moto G5 Plus, Android 8.1) and only when I rotate it counterclockwise to landscape.

Can't reproduce this on Android 8 / 8.1 emulators (API versions 26 and 27).

**Comment by joshuad31** [comment] 2021-09-23 14:37
@tuomas2 Does not fix issue
![Screenshot_20210923-093407_Bible Study](https://user-images.githubusercontent.com/5976059/134527602-613ebdd5-4409-42e2-ae1e-c2b5f8b85701.jpg)

Willing to do the following:
1. Upgrade from Android 8.0
2. try another build
3. Install tool for remote access
4. Generate bug report

**Comment by tuomas2** [comment] 2021-09-23 14:42
> 3\. Install tool for remote access

Which tool do you have in your mind?

**Comment by tuomas2** [comment] 2021-09-23 14:43
Let me make another simple test build...

**Comment by joshuad31** [comment] 2021-09-23 14:52
@tuomas2 I'm not sure if teamviewer will work.

Also, you may have to realize that this upgrade cannot be for all phones. 3.3 is quite good. I used every feature and I never wanted anything more than that.
1. I had more than 50 bookmark lists of verses about different biblical themes
2. I found a voice I liked and I had it read large portions of the bible to me
3. It was my preferred version to read from due to its very fast loading times
4. It was my preferred version for searching because I could search for a phrase, for "all words" and I could use the asterisk at the end of a word.
5. It allowed me to find all the verses to write this blog post:
https://joshuad31.com/faith-in-christ-vs-christian-works-e80f60681b1c

**Comment by tuomas2** [comment] 2021-09-23 15:07
I prepared some new test builds. I'm testing tweaking some toolbar style related things, to see if something helps.

- https://github.com/AndBible/and-bible/releases/tag/build-605-toolbarfix-blue-toolbar
- https://github.com/AndBible/and-bible/releases/tag/build-605-toolbarfix-red
- https://github.com/AndBible/and-bible/releases/tag/build-605-toolbarfix-secondary-removed
- https://github.com/AndBible/and-bible/releases/tag/build-605-toolbarfix-them-fixes
- https://github.com/AndBible/and-bible/releases/tag/build-605-toolbarfix-theme-fixes-2

Please test each of these builds and give screenshot if there's anything that is different from normal build.

~0 more builds are still coming. Posting links when they are ready.~

**Comment by tuomas2** [comment] 2021-09-23 15:57
(BTW we have had similar (though maybe not same root cause) issue in 3.3 too #417)

**Comment by tuomas2** [comment] 2021-09-23 15:58
> I prepared some new test builds. I'm testing tweaking some toolbar style related things, to see if something helps.
> 
> * https://github.com/AndBible/and-bible/releases/tag/build-605-toolbarfix-blue-toolbar
> * https://github.com/AndBible/and-bible/releases/tag/build-605-toolbarfix-red
> * https://github.com/AndBible/and-bible/releases/tag/build-605-toolbarfix-secondary-removed
> * https://github.com/AndBible/and-bible/releases/tag/build-605-toolbarfix-them-fixes
> * https://github.com/AndBible/and-bible/releases/tag/build-605-toolbarfix-theme-fixes-2
> 
> Please test each of these builds and give screenshot if there's anything that is different from normal build.
> 
> ~0 more builds are still coming. Posting links when they are ready.~

@joshuad31 can you test the above builds?

**Comment by tuomas2** [comment] 2021-09-23 15:58
(and/or @uniqueid001)

**Comment by joshuad31** [comment] 2021-09-23 16:31
@tuomas2 I tried all of them. I saved a few screenshots as proof. None of them created any changeL
![Screenshot_20210923-112441_Bible Study](https://user-images.githubusercontent.com/5976059/134547327-ab642da1-e887-4891-b575-1aa2f1ff9fc3.png)

**Comment by joshuad31** [comment] 2021-09-23 16:36
@tuomas2 Honestly I think you would be better served creating tools that give users better choices and more agency and freedom to choose rather than trying to make a "perfect" system. What users WANT is to have their own personal preferences respected. They don't want a "perfect" app, they want an app that works for them.

My advice is:
1. As soon as the update takes place, make it VERY EASY for the user to roll back to the previous version within 1 minute if they don't like it.
2. Stop supporting the users with the previous version with any updates or bug fixes.

I know developers hate to do this but this is what makes users happy when the developers give them agency, choice, freedom, the ability to express their preferences and opinions.

not everyone wants the latest and greatest. People want what works for them. Your energy would be better spent designing this kind of system.

**Comment by joshuad31** [comment] 2021-09-23 16:38
@tuomas2 Once you create the rollback update please let me install and test it. This will save me a few minutes but it will save other users hours of frustration and emotional turmoil.

**Comment by tuomas2** [comment] 2021-09-23 16:39
You tested so far:
1. theme fix 2 (42c7)
2. build-605-toolbarfix5 [this was old one) (4e12)
3. theme fixes (fd3c)

These are still waiting to be tested:
- https://github.com/AndBible/and-bible/releases/tag/build-605-toolbarfix-blue-toolbar
- https://github.com/AndBible/and-bible/releases/tag/build-605-toolbarfix-red
- https://github.com/AndBible/and-bible/releases/tag/build-605-toolbarfix-secondary-removed

**Comment by joshuad31** [comment] 2021-09-23 17:09
@tuomas2 As I said previously I tested all of them but I just didn't take screenshots for each one. Since you insisted I have taken more screenshots. As I said I don't think your efforts are well served when used in this way. You should pray about this.
![Bible Study](https://user-images.githubusercontent.com/5976059/134552724-600758ae-ce80-4712-a57f-049fd87b97f9.jpg)

**Comment by tuomas2** [comment] 2021-09-23 17:14
> @tuomas2 As I said previously I tested all of them but I just didn't take screenshots for each one. Since you insisted I have taken more screenshots. 

Thank you. Sorry, I did not notice that you said you already tested them all. I just noticed 3 screenshots.

**Comment by timbze** [comment] 2021-09-23 17:30
> this is what makes users happy when the developers give them agency, choice, freedom, the ability to express their preferences and opinions

This is why when I get a new phone and start installing apps, the first thing I do is disable all automatic updates, including OS updates if possible. Then I will occasionally look through the available updates and update those that I want to.

Play Store is not designed to be able to do easy roll-backs. There might be hacks that we could use, but Play Store will still update you again unless you disable automatic updating either for the app specifically or for all apps.

Since this is an open source, free project, anyone is free to take a previous version and modify if they want, or even upload a different version to Play Store that never updates. But that is not the purpose of this project.

Even though roll-back might be the best option for you, we still have to fix the issue so that other users with the same type of phone that you have won't have the issue. Thank you for the time you are giving in sending bug reports and testing, etc. You may not believe it, but that is the most helpful thing that you can be doing for the project at this point. God bless.

**Comment by tuomas2** [comment] 2021-09-23 18:10
If some other developer team member (@AndBible/developers) or contributor (@AndBible/contributors) 
has time to try to fight this bug, please go ahead. At least this is pretty much something that you don't need to know much about And Bible source code to be able to help with this. Android experience might be more valuable here.

I won't have much time for this in the upcoming days.  Most likely I can return to this issue on thursday 30th september. 

Prayers are welcome too.

**Comment by joshuad31** [comment] 2021-09-23 18:34
> Since this is an open source, free project, anyone is free to take a previous version and modify if they want, or even upload a different version to Play Store that never updates. But that is not the purpose of this project.
> 
> Even though roll-back might be the best option for you, we still have to fix the issue so that other users with the same type of phone that you have won't have the issue. Thank you for the time you are giving in sending bug reports and testing, etc. You may not believe it, but that is the most helpful thing that you can be doing for the project at this point. God bless.

I think that this deserves a moment of consideration. If the whole entire world is headed off a cliff I really don't think it's a good idea to follow along and jump right off.

The purpose of your project is to serve the Lord. This will require that you contact him through prayer in order to know what you should do to serve the believers.

What I proposed was very similar to the experience a user has when they attempt to change their resolution settings on their monitor. Through years of experience, the creators of monitors have learned that locking a user into changes even they themselves make is a bad idea because of the potential harm that users will "shoot themselves in the foot." This is why when a monitor setting is adjusted it reverts back to the previous setting unless the user takes an action to avoid the user being locked into a change that renders their screen unviewable.

Good design prevents users from suffering loss and bad design results in frustrated users. Even if Google itself is against good design this does not make them right. The highest form of design always seeks to mitigate user harm and frustration.

People think what I say is foolish because they think, "how much harm could be done to a user if their bible app stops working." Well if that is the primary source of their spiritual nourishment and they lose several hours trying to find an alternative or attempting to fix the problem then this is several hours they don't have to gain spiritual nourishment and growth.

For some people, this app is their primary source of spiritual nourishment. If it stops working then they will for a period stop eating and stop growing. Given that this is true I think you should optimize not for new and improved features but instead, you should seek to maximize the number of hours believers use the app to eat spiritual food and to grow in the Lord.

I don't care what Google does or does not do. They do not love the Lord and they could care less about the impacts of the decisions they make on their users. They also don't believe that they will ever have to account for the decisions they have made unless they break national laws.

But believers must answer to a higher authority and they should seek to maximize the amount of time other believers spend reading the bible. I'm sure that you care very much about this and I'm also sure you will pray about this.

I'm not making a judgment about your effort to improve the app but I really don't think you should use Google's policies as an excuse to avoid outcomes where believers put down the app and stop reading and thus stop growing. If 10% of your user base stops using the app after the upgrade then I'm not sure if you really optimized for the best outcome.

My advice is to simply create code that identifies which version of android and phone type the user has and then the "upgrade" will decide if it should implement the new features or not.

think of it as a switching system between 3.3 layout and 4.0 layout within 4.0 upgrade. Google's policies do not prevent you from implementing code that would work in this way and this type of code will allow you to maximize the number of believers who continue to use the app on older phones for several years into the future.

Optimize and maximize for the right thing and I am certain the Lord will be well pleased with your efforts. Optimize for the wrong thing and I don't think the Lord's presence will be with you in this effort.

Just my opinion, but I think I also have the spirit of the Lord.

**Comment by tuomas2** [comment] 2021-09-23 19:16
I created another ticket, strictly for the bug issue topic #1756. Feel free to continue other discussion here.

**Comment by timbze** [comment] 2021-09-23 19:53
@joshuad31 thanks for your input, we do consider it.

I don't think you understand the technicalities behind programming. I'm not saying that we care what Google thinks. The issue is what system is there. We have to make decisions and strike balances when there's things that would make a big difference in how much time is spent. For example, the upgrade from 3.3 to 4.0, in my estimate, probably has taken more than 500 hours of work (maybe even more than 1000). All volunteered.

It is not feasible to create an app that basically has 2 apps in 1. Everything changed from 3.3 to 4.0; database, backend code, and many things in between. The change is not just "switching a layer".

Even as "bad" as the experience was for you, there have already been thousands of devices upgraded with only a few other complaints. Most people are happy when we show them where the "missing" feature is (aka something changed).

We're sorry you had the bad experience, but even though you feel like this, it does not make it that the majority feels like this. Many people are happy for better highlighting, better notes, study pads, and the many other improved features in this app.

If you want to stay on 3.3 that is understood and acceptable with us. We want to make improvements for those who want it.

**Comment by agrogers** [comment] 2021-09-24 02:50
Hi Joshua

I think Timmy has explained the challenges we face quite well. Providing
one app that keeps ALL old features intact AND adds many new features is
extremely difficult. This is true for large organisations and small. This
project is made by a handful of volunteers using their spare time - so such
a feature is impossible.

The solution for you was to disable automatic updates in the Play Store. I
think you have probably got that set the way you need it now.

Thanks for your help troubleshooting this issue. We really appreciate it
when people who have been using And Bible for a long time give back a
little to the project. We do get the occasional message of sincere
gratitude from very happy users. It's a nice reward for the 1000s of hours
spent making the app with no financial remuneration at all. But more often
we get complaints about something not working correctly or worse, a
negative public review. It does feel very ungrateful to me when users who
have spent $0.00 complain without expressing some gratitude first. But
alas, the Lord Himself went unthanked so we are in good company :)

We hope to get the issue you are facing fixed soon. Thanks again for your
assistance with this. These issues are reallllllly hard to fix when we
don't have the problem device sitting on our desk.

Cheers
Andrew

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by uniqueid001** [comment] 2021-09-25 03:51
> (and/or @uniqueid001)

I tried several of your tags, and all still exhibit the issue.  I did notice the red half of the toolbar in the one revision.

**Closed as completed** 2021-09-26 21:00 UTC
Labels: Type: Discussion

**Comment by timbze** [comment] 2021-09-26 21:02
Any further information on this issue can be added on #1756
