### ISSUE TITLE
Bible reference shown wrong

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#416] opened 2019-07-25 06:52 UTC
Via email:

> 
> In the past:
> * I read a verse.
> * I click to check a commentary for the verse.
> * If the commentary has a cross-reference, I click it.
> * A small window pops up in the bottom half.
> * After reading the verse, I close the window.
> * If I'm done with the commentary, I hit 'back' to get back to the Bible version that I was reading.
> * So, in all, a total of 3 clicks to get back to the verse AFTER navigating into a commentary with cross-reference.
> 
> What's happening now (1st 5 steps are the same):
> * I read a verse.
> * I click to check a commentary for the verse.
> * If the commentary has a cross-reference, I click it.
> * A small window pops up in the bottom half
> * After reading the verse, I close the window. HERE IS WHERE THINGS CHANGE. Previously, when I closed the window, the top bar shows what's currently on the screen — in this scenario, it used to show the commentary title. But now, it still shows the title of the closed window. So, when I hit 'back', the titles change, but the main screen stays the same. (Compare attached screenshots. You will see that in one of them, the main content doesn't match the title in the top bar.)
> * Here's a workaround. After closing the cross-reference window, tap anywhere on the current screen. Then the top bar shows the correct/current title.  THEN, when I hit 'back', it goes back to the Bible version that I was reading.
> * So, that's a total of 4 clicks to get back to the verse AFTER navigating into a commentary with cross-reference.
>

**Comment by timbze** [comment] 2019-07-28 21:38
I think this is already fixed in 7dec48064d954c5d7a3fb6d6fe3cbcfd4df00ff3. I can't reproduce it.

**Comment by tuomas2** [comment] 2019-07-29 07:11
Can you @bvahedy verify if this is fixed? Should be in 313 (and already some earlier buidl)

**Comment by bvahedy** [comment] 2019-07-29 22:01
Yes, this is or had been fixed in the past. The screen title is correct
after closing the window without taping the screen.

**Closed** 2019-07-30 08:53 UTC
Labels: Type: Bug
