### ISSUE TITLE
Bookmark navigation issue

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#442] opened 2019-11-09 12:45 UTC
**To Reproduce**
1. Open bookmarks screen and go to a bookmark, Bible window opens
2. Press back button on device, bookmark window is opened again
3. Select another bookmark, Bible window opens again, but passage that is open does not change, the previously selected bookmark stays open

**Expected behavior**
The newly selected bookmark should be navigated to.

**Smartphone (please complete the following information):**
 - Device: LG G6
 - OS: Android 8.0

**Comment by bvahedy** [comment] 2019-11-09 16:54
Tim,
I am running beta 316 and am not able to reproduce this. I remember Tuomas
fixed a bug where if you have the bookmark list opened holding the devices
back button does not do anything and that is how it is behaving for me.

What version are you running and if you are on beta 316, may be a clean
install will fix the issue.

Ben

**Comment by timbze** [comment] 2019-11-12 01:05
Hi Ben, the instruction to press back button is when Bible screen is open. I tested this on my android 8 and also emulator android 9 and both had same issue

**Comment by bvahedy** [comment] 2019-11-12 06:36
Ok, I can reproduce this, I miss understood the steps. So this happens only when you are in the bookmark window and you select a passage and the back button takes you back to the bookmark window.
It won't happen if the back button does not take you back to the bookmark window.

**Comment by tuomas2** [comment] 2019-11-21 16:40
Reproduced with 318.3

**Comment by tuomas2** [comment] 2019-11-21 17:12
Will be fixed in 318.3

**Closed by tuomas2** 2019-11-21 17:11 UTC
Labels: Prio: Major, Type: Bug

**Comment by bvahedy** [comment] 2019-11-22 06:51
Verified fix in build 319.1
