### ISSUE TITLE
I got an error when trying to delete a bible document in the new documents interface 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#612] opened 2020-04-13 21:11 UTC
Just went to the new documents window (which looks good - well done).

Long clicked the Bible I didn't need - YLT 1988

Pushed the delete button at the top. 

Got an error which is attached.

**Comment by agrogers** [comment] 2020-04-13 21:12
#
[logcat.txt.gz](https://github.com/AndBible/and-bible/files/4471887/logcat.txt.gz)

Now its attached.

**Comment by tuomas2** [comment] 2020-04-14 07:36
Hmm. Unfortunately log does not contain stack trace of the error... only these two lines. 

04-14 07:02:56.963 14400 14400 D DocumentSelectionBase: Deleting:YLT
04-14 07:02:56.973 14400 14400 D Dialogs : showErrorMesage message:An error has occurred

**Comment by tuomas2** [comment] 2020-04-14 07:37
I'll improve error logging.

**Comment by tuomas2** [comment] 2020-04-14 07:41
I tried to reproduce, but couldn't reproduce. 
Improved error logging, so that we get better logcat if you can reproduce this still in beta build 362 (releasing later today).

**Comment by agrogers** [comment] 2020-04-14 22:51
Got the update. Thanks. Here is the new log file. 
[logcat.txt.gz](https://github.com/AndBible/and-bible/files/4478172/logcat.txt.gz)

It looks to be 4k larger so hopefully it has what you want.

**Comment by agrogers** [comment] 2020-04-14 22:55
I just tested some more and it is only that one bible that I have a problem deleting. I tried deleting a few others including the second YLT and had no error. Hope that helps. 

![IMG_20200415_085250](https://user-images.githubusercontent.com/13920678/79281757-c1668f00-7ef6-11ea-944c-3e9a73ea2830.jpg)

**Comment by bvahedy** [comment] 2020-04-15 00:08
I'm unable to duplicate this error as well, I'm using build 362 beta. Can you try a fresh install and see if the problem goes away.

**Comment by agrogers** [comment] 2020-04-15 00:33
I posted an update to the issue in git. I discovered it only happens with
the YLT 1898 version.

**Comment by tuomas2** [comment] 2020-04-15 06:21
> Got the update. Thanks. Here is the new log file.
> [logcat.txt.gz](https://github.com/AndBible/and-bible/files/4478172/logcat.txt.gz)
> 
> It looks to be 4k larger so hopefully it has what you want.

Are you sure this was produced with build 362? Because error is not logged properly there. I can't find line "Deleting document crashed" that should have been printed from net/bible/android/view/activity/base/DocumentSelectionBase.kt:487.  (Clearly there's logging from line 481, so I can't see why error would not be logged properly)

**Comment by tuomas2** [comment] 2020-04-15 06:22
and actually your screenshot also shows that it's older build.

**Comment by tuomas2** [comment] 2020-04-15 06:23
You can download latest build from https://drive.google.com/drive/folders/1LpUarFDZG8niDVC7JJufs0odV33s1z8D

Google Play comes about one day late normally due to Google Play review system.

**Comment by agrogers** [comment] 2020-04-15 10:11
Oh, when I opened it this morning it told me I had a new version installed.
I just assumed it was the latest. I will double check.

**Comment by agrogers** [comment] 2020-04-15 10:41
OK, just installed the latest version. Error is still there. Log attached.
Remember it is just for that one bible document. The others I tried deleted
fine.

**Comment by tuomas2** [comment] 2020-04-15 11:53
Attach log manually to issue comment. I think attachment was lost.

**Comment by agrogers** [comment] 2020-04-15 22:37
Log attached this time. 
[logcat.txt.gz](https://github.com/AndBible/and-bible/files/4484029/logcat.txt.gz)

**Comment by tuomas2** [comment] 2020-04-16 07:05
It's manually installed document in jsword folder. I'm not sure what's wrong, but I think installing docs manually to jsword folder is somewhat experimental feature anyway, so go ahead and delete it manually :-) 

I'm not sure why it looks like you don't have permission to delete document on that directory with And Bible. It could be checked if deleting manually installed docs from jsword fails always. Though I'm thinking I'm probably not going to investigate this any further (thus closing now). 

```
04-15 20:38:29.671 21402 21402 D net.bible.service.sword.SwordDocumentFacade: Got bibles, Num=14
04-15 20:38:31.015 21402 21402 D DocumentSelectionBase: Deleting:YLT
04-15 20:38:31.043 21402 21402 E DocumentSelectionBase: Deleting document crashed
04-15 20:38:31.043 21402 21402 E DocumentSelectionBase: org.crosswire.jsword.book.BookException: Unable to delete: /storage/emulated/0/jsword/mods.d/ylt.conf
04-15 20:38:31.043 21402 21402 E DocumentSelectionBase: 	at org.crosswire.jsword.book.sword.SwordBookDriver.delete(SwordBookDriver.java:179)
04-15 20:38:31.043 21402 21402 E DocumentSelectionBase: 	at net.bible.service.sword.SwordDocumentFacade.deleteDocument(SwordDocumentFacade.kt:171)
04-15 20:38:31.043 21402 21402 E DocumentSelectionBase: 	at net.bible.android.control.document.DocumentControl.deleteDocument(DocumentControl.kt:162)
04-15 20:38:31.043 21402 21402 E DocumentSelectionBase: 	at net.bible.android.view.activity.base.DocumentSelectionBase$handleDelete$1.onClick(DocumentSelectionBase.kt:482)
04-15 20:38:31.043 21402 21402 E DocumentSelectionBase: 	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:172)
04-15 20:38:31.043 21402 21402 E DocumentSelectionBase: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-15 20:38:31.043 21402 21402 E DocumentSelectionBase: 	at android.os.Looper.loop(Looper.java:201)
04-15 20:38:31.043 21402 21402 E DocumentSelectionBase: 	at android.app.ActivityThread.main(ActivityThread.java:6810)
04-15 20:38:31.043 21402 21402 E DocumentSelectionBase: 	at java.lang.reflect.Method.invoke(Native Method)
04-15 20:38:31.043 21402 21402 E DocumentSelectionBase: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
04-15 20:38:31.043 21402 21402 E DocumentSelectionBase: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
04-15 20:38:31.044 21402 21402 D Dialogs : showErrorMesage message:An error has occurred
```

**Closed by tuomas2** 2020-04-16 07:05 UTC
Labels: Prio: Major, Type: Bug

**Comment by agrogers** [comment] 2020-04-17 06:06
Thanks for looking into this. And yes, i can delete it myself no problems.
Thanks again to your and your team who are working on this app. It's
awesome.
