### ISSUE TITLE
Eink version

### ISSUE THREAD

**Issue by brouty** [AndBible/and-bible#2658] opened 2023-06-23 04:17 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I would like to see options for eink friendly color scheme. Interface with black text on white background. And especially the bible book, chapter, and verse selecter to also be black text on white background. No colors. Gray scale when needed in place of color.

**Describe alternatives you've considered**

**Additional context**

**Comment by ildar** [comment] 2023-06-23 06:24
I'm always frustrated when I see the "bug reports" like this.
@brouty , can you share what kind of a device you have? The Android version
and such?

**Comment by tuomas2** [comment] 2023-06-23 07:12
Actually this is duplicate of #1126

**Closed as completed by tuomas2** 2023-06-23 07:12 UTC
Labels: Type: Feature

**Comment by tuomas2** [comment] 2023-06-23 07:23
> I'm always frustrated when I see the "bug reports" like this. @brouty , can you share what kind of a device you have? The Android version and such?

And no need to be frustrated.... Probably this was his first ever feature request ticket in Github. :-)
