### ISSUE TITLE
Gill missing some text

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#882] opened 2020-10-29 10:49 UTC
Gill's commentary on Judges, Jonah, and Philemon is not available. I've attached a screenshot of the books of the Bible available when I'm in a window connected to Gill's commentary. The other screenshot showing the "not found in document" message.

https://support.andbible.org/scp/tickets.php?id=161

**Comment by tuomas2** [comment] 2020-10-29 10:49
Should check if Xiphos shows these chapters

**Comment by timbze** [comment] 2020-10-29 12:58
I confirmed in diatheke that those 3 books have no content in the module

**Comment by tuomas2** [comment] 2020-10-29 13:21
Gill is not released in Crosswire repository. Should figure out who is maintaining it (Xiphos developer?) and where is the source text.

**Comment by timbze** [comment] 2022-06-09 18:13
Closing as duplicate of #2166

**Closed as completed by timbze** 2022-06-09 18:13 UTC
Labels: Prio: Major, Module issue
