### ISSUE TITLE
show search result window as a normal window and item can be copied

### ISSUE THREAD

**Issue by JacobZy** [AndBible/and-bible#899] opened 2020-11-19 02:46 UTC
Is your feature request related to a problem? Please describe.
I'm always frustrated when using search function or 'find all occurrences' in strongsRealHebrew dictionary. It will Pop up an new window, and after click one item of the list will change the source  window . and no way back to the search result window to click another link. also so far I find no way to copy the item of the search result list.

Describe the solution you'd like
1. when using search function or 'find all occurrences' in strongs dictionary, the result list  show in a normal window and the bible/dictionary window remain show still, when click each search item show the according bible in another  not pined window.
2. the search result  items can be copied.

Describe a window handle method you've considered
Maybe it will be easy to handle the windows management by maintaining different windows type such as mainBible/commentary&crossref/dictionary/searchRresult/activeBible(the active panel show according location bible context when click verse links in other comm/dict/ref module)

**Comment by timbze** [comment] 2020-11-19 16:52
@JacobZy thanks for your suggestions! :) This has been suggested before so I will close it as duplicate of #611. If you feel that anything else needs to be added you can add a comment in #611

**Closed as completed by timbze** 2020-11-19 16:52 UTC
Labels: Type: Feature, Prio: Minor, Status: Preliminary
