### ISSUE TITLE
Proposal: Alert users before the next major update through an intrusive message

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1788] opened 2021-10-03 11:53 UTC
Before the next major release I think it would be good to add a final minor release that throws up a BIG message that says "We will be releasing a new update very soon. If you have auto updates on you will be update automatically. Here are some of the cool new features that are coming...."

**Comment by timbze** [comment] 2021-10-03 13:27
That is a great idea. That way users can be instructed how to disable auto updates if they want to

**Comment by agrogers** [comment] 2021-10-04 01:31
Yeah, that was my thought too. Also good to let people know what they can
expect before it happens.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by bvahedy** [comment] 2021-10-04 02:26
How do we do that if AB is used as an offline app, unless we create a
version that when they auto update and  open the app  it shows them the msg
that says next update has.... And if they don't want it to disable auto
update.
But even that only works for those who haven't turned off auto update.

**Comment by agrogers** [comment] 2021-10-04 05:58
My thought was that the complaints we have had have come from only  those
who are connected and have auto updates on. So the alert will target the
right people.

**Comment by tuomas2** [comment] 2021-10-04 18:06
I just saw this happening in finnish newsmedia app. 

We could consider doing that. But only if we do something huge like 4.0. 4.1 probably does not need.

**Comment by tuomas2** [comment] 2023-08-26 11:02
Duplicate of #2353

**Closed as completed by tuomas2** 2023-08-26 11:02 UTC
Labels: Type: Feature
