### ISSUE TITLE
personal note text window does not scroll downward when keyboard is active. 

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#230] opened 2019-01-22 16:37 UTC
When entering text in a personal note for a verse (using the My Note feature), the text does not scroll. Or rather, it scrolls up if you type enough text, but then you can't scroll down in order to see the beginning of the text.

**Comment by tuomas2** [comment] 2019-01-22 17:13
Now the text is scrollable. Scrollbar still not visible. I'll leave this as I'm planning to re-organize "My notes" in the future (#188).

**Comment by bvahedy** [comment] 2019-01-22 19:30
Ok, I was able to reproduce this. This does not happen when the keyboard is minimized. Once the keyboard is up you can't scroll the note text.

**Comment by bvahedy** [comment] 2019-01-24 17:24
I'm relableing  this to be more clear, I also bumped down it's priority since the user can still function by minimizing the keyboard and moving to where they want to make the change.

**Comment by bvahedy** [comment] 2019-02-14 20:19
This bug was fixed but now it's back.

**Comment by tuomas2** [comment] 2019-02-15 07:27
Will be fixed in 298

**Comment by bvahedy** [comment] 2019-02-15 21:46
We are getting closer, but scroll not able to scroll when keyboard is active. So, I'm reporting this ticket.

**Comment by tuomas2** [comment] 2019-02-16 16:36
From play beta feedback:
> Issue #230 .. the cursor changes location when scrolled out of view. It should remain where it is until the user changes it. If a word is selected, it behaves correctly.

**Comment by bvahedy** [comment] 2019-02-16 16:40
I think this is related to the scroll issue. When trying to slide up is where it changes the curser position.

**Comment by tuomas2** [comment] 2019-02-18 18:00
From user via email:

> ► The cursor changes location when scrolled out of view. It should remain where it is until the user changes it. If a word is selected, the cursor (selection) behaves correctly. To reproduce: notes that are long enough to scroll when the keyboard is hidden.
> 
> ► Scrolling is broken when the keyboard is visible .. for notes that are too short to scroll when the keyboard is hidden, but long enough to scroll when the keyboard is visible.

**Comment by timbze** [comment] 2021-08-04 15:35
Obsolete in 4.0

**Closed by timbze** 2021-08-04 15:35 UTC
Labels: Affects: 3.0, Prio: Minor, Type: Bug
