### ISSUE TITLE
Clicking links to footnotes/x-refs for titles goes to footnotes/x-refs for verse 1

### ISSUE THREAD

**Issue by eugenern** [AndBible/and-bible#856] opened 2020-10-01 04:31 UTC
**Describe the bug**
I'm trying to open the footnotes and cross-references for the title in a chapter of Psalms, but am taken to those for verse 1 instead.

**Bug was found on And Bible version**
3.3.391#b05b10c (built 17/09/20 16:04:46)

**To Reproduce**
1. Go to a chapter whose title contains a footnote or reference, e.g. Psalm 77.
2. Click on one of the links in the title.
3. The screen goes to footnotes and references for verse 1 of the chapter. It's possible to swipe along the top/the refs to those of other verses, but not possible to swipe left from verse 1.

**Expected behavior**
A screen for the footnotes/refs in the chapter title.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: motorola moto g(7) power
 - OS: Android
 - Version 10 (SDK 29)

**Additional context**

**Comment by tuomas2** [comment] 2020-10-01 07:42
Can you name the bible translation you are using?

**Comment by eugenern** [comment] 2020-10-01 07:52
I'm using ESV. The document description says "ESV2011 English Standard Version with Strongs numbers. (NRSV)".

**Comment by bvahedy** [comment] 2020-10-01 16:11
We had issues creating footnotes for titles which was referred to as verse zero. To my knowledge the option for creating notes for titles is removed and you can only create notes for verse 1 and forward. If you are seeing a pencil on your title you had this created before the big was fixed, just delete that note and that will remove it from your database.  Since many Bibles translations don't have titles for chapters it would make sense not to allow the creation of a note for verse zero.

**Comment by tuomas2** [comment] 2020-10-01 16:21
@bvahedy I think he is referring to footnotes / crossreferences (provided by module, i.e. ESV), not My Notes, that are created by user.

**Comment by bvahedy** [comment] 2020-10-01 19:42
Ok I see. I was able to see the issue, but I don't think it's a big issue as it displays the right footnote ref., It just displays the book-chapter-verse it's from, which is correct. The translators really shouldn't have put a footnote in the title.

**Comment by eugenern** [comment] 2020-10-04 07:20
I think it'd be useful to able to see the title's/subtitles' footnotes, for example in Psalm 6 where the subtitle has one crossreference to 1 Chronicles 15:21 and one footnote explaining Sheminith to be "Probably a musical or liturgical term", neither of which would be visible from the app. But it does display the footnote ref correctly, so it's possible to work around the issue by checking those somewhere else.

**Comment by timbze** [comment] 2021-08-03 17:44
Confirmed this issue no longer exists in 4.0-beta. I don't think this will be fixed in 3.3, but if @tuomas2 decides differently he can re-open

**Closed as completed by timbze** 2021-08-03 17:44 UTC
Labels: Type: Bug, Prio: Major, Obsolete in 4.0
