### ISSUE TITLE
Don't show verses correctly in MyBible module in Daniel's Book

### ISSUE THREAD

**Issue by pepaulo** [AndBible/and-bible#2852] opened 2023-09-14 16:29 UTC
Don't display the verses of Daniel 3 from 24 at 90, and the chapters 13 and 14 on MyBible module.

**Comment by tuomas2** [comment] 2023-09-14 16:49
duplicate of https://github.com/AndBible/and-bible/issues/2747?

**Comment by pepaulo** [comment] 2023-09-14 18:23
@tuomas2 Yes. This is part of a bigger bug concerned to use the MyBible modules in other versification, not in KJA

**Comment by tuomas2** [comment] 2023-09-14 18:51
duplicate of https://github.com/AndBible/and-bible/issues/2747

**Closed as completed by tuomas2** 2023-09-14 18:51 UTC
