### ISSUE TITLE
Window synch fails on going to a passsges from bookmarks... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#336] opened 2019-03-12 18:23 UTC
To reproduce: 
(Note: this bug does not happen consistently)
1) open  two windows. 
2) make sure win. synch is checked.
3) for the bottom window choose a Bible that only has old testament, e. g. JPS
4) from bookmarks go to a passage in the NT
5) again go to the bookmarks and  choose a passage from the OT.
Check the book/verse ref. on the menu bar. They may not mach the passage from the bookmark. If you don't see this issue keep going to diff. passages from your bookmark and it eventually happens. Don't really know exactly want triggers this issue and it's not consistent.

**Comment by tuomas2** [comment] 2019-03-12 18:46
I think we can keep this bug issue in one ticket. This is duplicate of #324

**Closed by tuomas2** 2019-03-12 18:46 UTC
Labels: Type: Bug
