### ISSUE TITLE
History item fails to jump to proper passage... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#424] opened 2019-08-17 19:06 UTC
To reproduce:
1) With two windows open, turning off the sync  in the second window.
2) tap on top window and go to  Isa 40:8 and move a few verses down.
3) tap on the bottom window and go to Exod 8:1.
4)  tap on window settings for the bottom window and turn on sync.
5) tap on top window, then press and hold the device back button to bring up history for the top window and select Isa 40:8.

What happens:
 The top window fails to jump to the passage and the top menu still displays Exo 8:1.

Expected result:
When selecting a window and invoking it's history, the active window should take priority and jump to the passage selected from history.

**Comment by tuomas2** [comment] 2019-10-17 12:46
Can't reproduce this any more. Possibly fixed due to other js interface fixes. 

Fixed in build 315.

**Closed by tuomas2** 2019-10-17 12:46 UTC
Labels: Type: Bug

**Comment by bvahedy** [comment] 2019-10-18 03:27
Seems to be fixed in build 315.
