### ISSUE TITLE
Fancy bible-verse-exported-with-nice-colors-and-background-image feature?

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1168] opened 2021-06-19 13:24 UTC
I noticed that this feature was pretty comprehensive in a few Bible apps. Lots of background images, blurring of images, brightness settings, choice of fonts and colors and sizes etc. Is this something we want in And Bible?

![image](https://user-images.githubusercontent.com/13920678/122643847-77f67d00-d155-11eb-950c-29bc0c12cd45.png)

**Comment by tuomas2** [comment] 2021-06-19 13:45
If someone creates such a feature I'm for it :-) But I'm not interested personally.

**Comment by bvahedy** [comment] 2021-06-19 17:32
More features like this means a bigger app size. I'm more interested in the
substance of a verse study than making it look nice for someone else. This
is just my take on it. But I do appreciate and respect your thoughts.

**Comment by agrogers** [comment] 2021-06-20 04:39
I probably wouldn't use a feature like this either. And it is a feature not
really in line with a study bible. Hence the reason I asked the question.

**Comment by tuomas2** [comment] 2022-11-17 16:29
Duplicate of #2355

**Closed as completed by tuomas2** 2022-11-17 16:29 UTC
Labels: Type: Feature, Prio: Minor, Status: Preliminary
