### ISSUE TITLE
Highlight the word that I searched for

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1244] opened 2021-07-07 08:32 UTC
This thought originally came from when i did a 'Find all occurrences' of a Greek word. It shows me the list of verses it found.  But it is a bit hard to tell which word it actually found.

But it also applies to a normal search.  That is:

1. When a user searches for a word or phrase...
2. Highlight the particular word or phrase that was found in the verse
2. Also do that for the Greek/Hebrew words found - but ideally not by showing the numbers (as per the example below) but by highlighting the word itself. Or maybe both if both text and numbers are shown.

![image](https://user-images.githubusercontent.com/13920678/124726909-8adcc000-df51-11eb-8b5f-c5546de2afa2.png)

**Comment by timbze** [comment] 2021-07-07 11:15
Also in #186

**Comment by agrogers** [comment] 2021-07-07 11:46
Ah, so it is. I even commented on that issue as well!

**Comment by tuomas2** [comment] 2021-07-07 16:36
Duplicate of #186

**Closed as completed by tuomas2** 2021-07-07 16:36 UTC
Labels: Type: Feature, Prio: Minor, Status: Preliminary
