### ISSUE TITLE
jsword folder is not seen in build 305 under Android 10 OS

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#908] opened 2020-11-30 01:48 UTC
Using build 399 in Android 10 the jsword folder is not read when though storage permissions is given.
I tried build 3.1.305 and it seems to read the folder correctly. So the big exists in build 399.
This is what it should look like: (305 build)
![Screenshot_20201129-173002_And Bible](https://user-images.githubusercontent.com/46405809/100560651-55f5e580-326b-11eb-9794-d6bbba96c06f.jpg)

This is the wrong format: (399 build)
![Screenshot_20201129-173701_Bible Study](https://user-images.githubusercontent.com/46405809/100560724-8fc6ec00-326b-11eb-9c75-03098445ad6a.jpg)

**Comment by tuomas2** [comment] 2020-11-30 06:33
Android 10, If I remember correctly, does not allow any more free access to any folder. So we need to stick to our app folder in Android/ subfolder.

**Comment by bvahedy** [comment] 2020-11-30 07:56
But build 305 under Android 10 works as you can see in the first screenshot above. It may be the way build 399 is reading the storage directory path.

**Comment by bvahedy** [comment] 2020-11-30 08:28
It could also be looking for an exact case sensitive folder name. I noticed that it does that with module names in the Android/data/... Subfolders.
I remember this issue happening in older builds and you fixed it, somehow the bug came back.

**Comment by tuomas2** [comment] 2020-11-30 09:14
It is possible that still in Android 10 apps with target sdk < 29 work. But not any more as we target to 29.

https://developer.android.com/about/versions/10/privacy/changes

**Comment by bvahedy** [comment] 2020-11-30 15:44
I do not think that is the case, since the app is already reading/writing to local storage for database backup/restore.
Also there is nothing in the sdk 29 that prevents reading and recognizing local storage files, it talks about external storage.

**Comment by tuomas2** [comment] 2020-11-30 17:28
Ping @AndBible/developers ^

**Comment by JJK96** [comment] 2020-12-08 22:09
I can confirm this issue on my device.

**Comment by tuomas2** [comment] 2020-12-15 08:24
Also https://support.andbible.org/scp/tickets.php?id=249 (custom reading plans) @timbze

**Comment by ildar** [comment] 2020-12-15 08:39
Authentication Required

**Comment by tuomas2** [comment] 2020-12-15 10:04
> Authentication Required

That area is for developer team only. But original messages are (sometimes) useful for tracking down the issue so we always give reference to those tickets here.

**Comment by timbze** [comment] 2021-03-27 21:06
Related: #632

**Comment by tuomas2** [comment] 2021-04-22 07:14
This feature is disabled for Android 10+. #632 will fix this for Android 10+. This feature is mostly obsolete due to other improvements in develop. Closing this now.

**Closed as completed by tuomas2** 2021-04-22 07:14 UTC
Labels: Type: Bug, Prio: Major
